#!/bash/sh

ffmpeg -y -i ~/.keras/datasets/agree_considered/islf_agree_considered_%03d.png ~/.keras/datasets/islf_agree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/agree_continue/islf_agree_continue_%03d.png ~/.keras/datasets/islf_agree_continue.mpg
ffmpeg -y -i ~/.keras/datasets/agree_pure/islf_agree_pure_%03d.png ~/.keras/datasets/islf_agree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/agree_reluctant/islf_agree_reluctant_%03d.png ~/.keras/datasets/islf_agree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/aha-light_bulb_moment/islf_aha-light_bulb_moment_%03d.png ~/.keras/datasets/islf_aha-light_bulb_moment.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_bothered/islf_annoyed_bothered_%03d.png ~/.keras/datasets/islf_annoyed_bothered.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_rolling-eyes/islf_annoyed_rolling-eyes_%03d.png ~/.keras/datasets/islf_annoyed_rolling-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/arrogant/islf_arrogant_%03d.png ~/.keras/datasets/islf_arrogant.mpg
ffmpeg -y -i ~/.keras/datasets/bored/islf_bored_%03d.png ~/.keras/datasets/islf_bored.mpg
ffmpeg -y -i ~/.keras/datasets/compassion/islf_compassion_%03d.png ~/.keras/datasets/islf_compassion.mpg
ffmpeg -y -i ~/.keras/datasets/confused/islf_confused_%03d.png ~/.keras/datasets/islf_confused.mpg
ffmpeg -y -i ~/.keras/datasets/contempt/islf_contempt_%03d.png ~/.keras/datasets/islf_contempt.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_considered/islf_disagree_considered_%03d.png ~/.keras/datasets/islf_disagree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_pure/islf_disagree_pure_%03d.png ~/.keras/datasets/islf_disagree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_reluctant/islf_disagree_reluctant_%03d.png ~/.keras/datasets/islf_disagree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/disbelief/islf_disbelief_%03d.png ~/.keras/datasets/islf_disbelief.mpg
ffmpeg -y -i ~/.keras/datasets/disgust/islf_disgust_%03d.png ~/.keras/datasets/islf_disgust.mpg
ffmpeg -y -i ~/.keras/datasets/embarrassment/islf_embarrassment_%03d.png ~/.keras/datasets/islf_embarrassment.mpg
ffmpeg -y -i ~/.keras/datasets/fear_oops/islf_fear_oops_%03d.png ~/.keras/datasets/islf_fear_oops.mpg
ffmpeg -y -i ~/.keras/datasets/fear_terror/islf_fear_terror_%03d.png ~/.keras/datasets/islf_fear_terror.mpg
ffmpeg -y -i ~/.keras/datasets/happy_achievement/islf_happy_achievement_%03d.png ~/.keras/datasets/islf_happy_achievement.mpg
ffmpeg -y -i ~/.keras/datasets/happy_laughing/islf_happy_laughing_%03d.png ~/.keras/datasets/islf_happy_laughing.mpg
ffmpeg -y -i ~/.keras/datasets/happy_satiated/islf_happy_satiated_%03d.png ~/.keras/datasets/islf_happy_satiated.mpg
ffmpeg -y -i ~/.keras/datasets/happy_schadenfreude/islf_happy_schadenfreude_%03d.png ~/.keras/datasets/islf_happy_schadenfreude.mpg
ffmpeg -y -i ~/.keras/datasets/I_did_not_hear/islf_I_did_not_hear_%03d.png ~/.keras/datasets/islf_I_did_not_hear.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_care/islf_I_dont_care_%03d.png ~/.keras/datasets/islf_I_dont_care.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_know/islf_I_dont_know_%03d.png ~/.keras/datasets/islf_I_dont_know.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_understand/islf_I_dont_understand_%03d.png ~/.keras/datasets/islf_I_dont_understand.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_negative/islf_imagine_negative_%03d.png ~/.keras/datasets/islf_imagine_negative.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_positive/islf_imagine_positive_%03d.png ~/.keras/datasets/islf_imagine_positive.mpg
ffmpeg -y -i ~/.keras/datasets/impressed/islf_impressed_%03d.png ~/.keras/datasets/islf_impressed.mpg
ffmpeg -y -i ~/.keras/datasets/insecurity/islf_insecurity_%03d.png ~/.keras/datasets/islf_insecurity.mpg
ffmpeg -y -i ~/.keras/datasets/not_convinced/islf_not_convinced_%03d.png ~/.keras/datasets/islf_not_convinced.mpg
ffmpeg -y -i ~/.keras/datasets/pain_felt/islf_pain_felt_%03d.png ~/.keras/datasets/islf_pain_felt.mpg
ffmpeg -y -i ~/.keras/datasets/pain_seen/islf_pain_seen_%03d.png ~/.keras/datasets/islf_pain_seen.mpg
ffmpeg -y -i ~/.keras/datasets/remember_negative/islf_remember_negative_%03d.png ~/.keras/datasets/islf_remember_negative.mpg
ffmpeg -y -i ~/.keras/datasets/remember_positive/islf_remember_positive_%03d.png ~/.keras/datasets/islf_remember_positive.mpg
ffmpeg -y -i ~/.keras/datasets/sad/islf_sad_%03d.png ~/.keras/datasets/islf_sad.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_encouraging/islf_smiling_encouraging_%03d.png ~/.keras/datasets/islf_smiling_encouraging.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_endearment/islf_smiling_endearment_%03d.png ~/.keras/datasets/islf_smiling_endearment.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_flirting/islf_smiling_flirting_%03d.png ~/.keras/datasets/islf_smiling_flirting.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sad-nostalgia/islf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/islf_smiling_sad-nostalgia.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sardonic/islf_smiling_sardonic_%03d.png ~/.keras/datasets/islf_smiling_sardonic.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_triumphant/islf_smiling_triumphant_%03d.png ~/.keras/datasets/islf_smiling_triumphant.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_uncertain/islf_smiling_uncertain_%03d.png ~/.keras/datasets/islf_smiling_uncertain.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_winning/islf_smiling_winning_%03d.png ~/.keras/datasets/islf_smiling_winning.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_yeah-right/islf_smiling_yeah-right_%03d.png ~/.keras/datasets/islf_smiling_yeah-right.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_considering/islf_thinking_considering_%03d.png ~/.keras/datasets/islf_thinking_considering.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_problem-solving/islf_thinking_problem-solving_%03d.png ~/.keras/datasets/islf_thinking_problem-solving.mpg
ffmpeg -y -i ~/.keras/datasets/tired/islf_tired_%03d.png ~/.keras/datasets/islf_tired.mpg
ffmpeg -y -i ~/.keras/datasets/treudoof_bambi-eyes/islf_treudoof_bambi-eyes_%03d.png ~/.keras/datasets/islf_treudoof_bambi-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/agree_considered/kabf_agree_considered_%03d.png ~/.keras/datasets/kabf_agree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/agree_continue/kabf_agree_continue_%03d.png ~/.keras/datasets/kabf_agree_continue.mpg
ffmpeg -y -i ~/.keras/datasets/agree_pure/kabf_agree_pure_%03d.png ~/.keras/datasets/kabf_agree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/agree_reluctant/kabf_agree_reluctant_%03d.png ~/.keras/datasets/kabf_agree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/aha-light_bulb_moment/kabf_aha-light_bulb_moment_%03d.png ~/.keras/datasets/kabf_aha-light_bulb_moment.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_bothered/kabf_annoyed_bothered_%03d.png ~/.keras/datasets/kabf_annoyed_bothered.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_rolling-eyes/kabf_annoyed_rolling-eyes_%03d.png ~/.keras/datasets/kabf_annoyed_rolling-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/arrogant/kabf_arrogant_%03d.png ~/.keras/datasets/kabf_arrogant.mpg
ffmpeg -y -i ~/.keras/datasets/bored/kabf_bored_%03d.png ~/.keras/datasets/kabf_bored.mpg
ffmpeg -y -i ~/.keras/datasets/compassion/kabf_compassion_%03d.png ~/.keras/datasets/kabf_compassion.mpg
ffmpeg -y -i ~/.keras/datasets/confused/kabf_confused_%03d.png ~/.keras/datasets/kabf_confused.mpg
ffmpeg -y -i ~/.keras/datasets/contempt/kabf_contempt_%03d.png ~/.keras/datasets/kabf_contempt.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_considered/kabf_disagree_considered_%03d.png ~/.keras/datasets/kabf_disagree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_pure/kabf_disagree_pure_%03d.png ~/.keras/datasets/kabf_disagree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_reluctant/kabf_disagree_reluctant_%03d.png ~/.keras/datasets/kabf_disagree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/disbelief/kabf_disbelief_%03d.png ~/.keras/datasets/kabf_disbelief.mpg
ffmpeg -y -i ~/.keras/datasets/disgust/kabf_disgust_%03d.png ~/.keras/datasets/kabf_disgust.mpg
ffmpeg -y -i ~/.keras/datasets/embarrassment/kabf_embarrassment_%03d.png ~/.keras/datasets/kabf_embarrassment.mpg
ffmpeg -y -i ~/.keras/datasets/fear_oops/kabf_fear_oops_%03d.png ~/.keras/datasets/kabf_fear_oops.mpg
ffmpeg -y -i ~/.keras/datasets/fear_terror/kabf_fear_terror_%03d.png ~/.keras/datasets/kabf_fear_terror.mpg
ffmpeg -y -i ~/.keras/datasets/happy_achievement/kabf_happy_achievement_%03d.png ~/.keras/datasets/kabf_happy_achievement.mpg
ffmpeg -y -i ~/.keras/datasets/happy_laughing/kabf_happy_laughing_%03d.png ~/.keras/datasets/kabf_happy_laughing.mpg
ffmpeg -y -i ~/.keras/datasets/happy_satiated/kabf_happy_satiated_%03d.png ~/.keras/datasets/kabf_happy_satiated.mpg
ffmpeg -y -i ~/.keras/datasets/happy_schadenfreude/kabf_happy_schadenfreude_%03d.png ~/.keras/datasets/kabf_happy_schadenfreude.mpg
ffmpeg -y -i ~/.keras/datasets/I_did_not_hear/kabf_I_did_not_hear_%03d.png ~/.keras/datasets/kabf_I_did_not_hear.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_care/kabf_I_dont_care_%03d.png ~/.keras/datasets/kabf_I_dont_care.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_know/kabf_I_dont_know_%03d.png ~/.keras/datasets/kabf_I_dont_know.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_understand/kabf_I_dont_understand_%03d.png ~/.keras/datasets/kabf_I_dont_understand.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_negative/kabf_imagine_negative_%03d.png ~/.keras/datasets/kabf_imagine_negative.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_positive/kabf_imagine_positive_%03d.png ~/.keras/datasets/kabf_imagine_positive.mpg
ffmpeg -y -i ~/.keras/datasets/impressed/kabf_impressed_%03d.png ~/.keras/datasets/kabf_impressed.mpg
ffmpeg -y -i ~/.keras/datasets/insecurity/kabf_insecurity_%03d.png ~/.keras/datasets/kabf_insecurity.mpg
ffmpeg -y -i ~/.keras/datasets/not_convinced/kabf_not_convinced_%03d.png ~/.keras/datasets/kabf_not_convinced.mpg
ffmpeg -y -i ~/.keras/datasets/pain_felt/kabf_pain_felt_%03d.png ~/.keras/datasets/kabf_pain_felt.mpg
ffmpeg -y -i ~/.keras/datasets/pain_seen/kabf_pain_seen_%03d.png ~/.keras/datasets/kabf_pain_seen.mpg
ffmpeg -y -i ~/.keras/datasets/remember_negative/kabf_remember_negative_%03d.png ~/.keras/datasets/kabf_remember_negative.mpg
ffmpeg -y -i ~/.keras/datasets/remember_positive/kabf_remember_positive_%03d.png ~/.keras/datasets/kabf_remember_positive.mpg
ffmpeg -y -i ~/.keras/datasets/sad/kabf_sad_%03d.png ~/.keras/datasets/kabf_sad.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_encouraging/kabf_smiling_encouraging_%03d.png ~/.keras/datasets/kabf_smiling_encouraging.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_endearment/kabf_smiling_endearment_%03d.png ~/.keras/datasets/kabf_smiling_endearment.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_flirting/kabf_smiling_flirting_%03d.png ~/.keras/datasets/kabf_smiling_flirting.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sad-nostalgia/kabf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/kabf_smiling_sad-nostalgia.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sardonic/kabf_smiling_sardonic_%03d.png ~/.keras/datasets/kabf_smiling_sardonic.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_triumphant/kabf_smiling_triumphant_%03d.png ~/.keras/datasets/kabf_smiling_triumphant.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_uncertain/kabf_smiling_uncertain_%03d.png ~/.keras/datasets/kabf_smiling_uncertain.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_winning/kabf_smiling_winning_%03d.png ~/.keras/datasets/kabf_smiling_winning.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_yeah-right/kabf_smiling_yeah-right_%03d.png ~/.keras/datasets/kabf_smiling_yeah-right.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_considering/kabf_thinking_considering_%03d.png ~/.keras/datasets/kabf_thinking_considering.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_problem-solving/kabf_thinking_problem-solving_%03d.png ~/.keras/datasets/kabf_thinking_problem-solving.mpg
ffmpeg -y -i ~/.keras/datasets/tired/kabf_tired_%03d.png ~/.keras/datasets/kabf_tired.mpg
ffmpeg -y -i ~/.keras/datasets/treudoof_bambi-eyes/kabf_treudoof_bambi-eyes_%03d.png ~/.keras/datasets/kabf_treudoof_bambi-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/agree_considered/lekf_agree_considered_%03d.png ~/.keras/datasets/lekf_agree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/agree_continue/lekf_agree_continue_%03d.png ~/.keras/datasets/lekf_agree_continue.mpg
ffmpeg -y -i ~/.keras/datasets/agree_pure/lekf_agree_pure_%03d.png ~/.keras/datasets/lekf_agree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/agree_reluctant/lekf_agree_reluctant_%03d.png ~/.keras/datasets/lekf_agree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/aha-light_bulb_moment/lekf_aha-light_bulb_moment_%03d.png ~/.keras/datasets/lekf_aha-light_bulb_moment.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_bothered/lekf_annoyed_bothered_%03d.png ~/.keras/datasets/lekf_annoyed_bothered.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_rolling-eyes/lekf_annoyed_rolling-eyes_%03d.png ~/.keras/datasets/lekf_annoyed_rolling-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/arrogant/lekf_arrogant_%03d.png ~/.keras/datasets/lekf_arrogant.mpg
ffmpeg -y -i ~/.keras/datasets/bored/lekf_bored_%03d.png ~/.keras/datasets/lekf_bored.mpg
ffmpeg -y -i ~/.keras/datasets/compassion/lekf_compassion_%03d.png ~/.keras/datasets/lekf_compassion.mpg
ffmpeg -y -i ~/.keras/datasets/confused/lekf_confused_%03d.png ~/.keras/datasets/lekf_confused.mpg
ffmpeg -y -i ~/.keras/datasets/contempt/lekf_contempt_%03d.png ~/.keras/datasets/lekf_contempt.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_considered/lekf_disagree_considered_%03d.png ~/.keras/datasets/lekf_disagree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_pure/lekf_disagree_pure_%03d.png ~/.keras/datasets/lekf_disagree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_reluctant/lekf_disagree_reluctant_%03d.png ~/.keras/datasets/lekf_disagree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/disbelief/lekf_disbelief_%03d.png ~/.keras/datasets/lekf_disbelief.mpg
ffmpeg -y -i ~/.keras/datasets/disgust/lekf_disgust_%03d.png ~/.keras/datasets/lekf_disgust.mpg
ffmpeg -y -i ~/.keras/datasets/embarrassment/lekf_embarrassment_%03d.png ~/.keras/datasets/lekf_embarrassment.mpg
ffmpeg -y -i ~/.keras/datasets/fear_oops/lekf_fear_oops_%03d.png ~/.keras/datasets/lekf_fear_oops.mpg
ffmpeg -y -i ~/.keras/datasets/fear_terror/lekf_fear_terror_%03d.png ~/.keras/datasets/lekf_fear_terror.mpg
ffmpeg -y -i ~/.keras/datasets/happy_achievement/lekf_happy_achievement_%03d.png ~/.keras/datasets/lekf_happy_achievement.mpg
ffmpeg -y -i ~/.keras/datasets/happy_laughing/lekf_happy_laughing_%03d.png ~/.keras/datasets/lekf_happy_laughing.mpg
ffmpeg -y -i ~/.keras/datasets/happy_satiated/lekf_happy_satiated_%03d.png ~/.keras/datasets/lekf_happy_satiated.mpg
ffmpeg -y -i ~/.keras/datasets/happy_schadenfreude/lekf_happy_schadenfreude_%03d.png ~/.keras/datasets/lekf_happy_schadenfreude.mpg
ffmpeg -y -i ~/.keras/datasets/I_did_not_hear/lekf_I_did_not_hear_%03d.png ~/.keras/datasets/lekf_I_did_not_hear.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_care/lekf_I_dont_care_%03d.png ~/.keras/datasets/lekf_I_dont_care.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_know/lekf_I_dont_know_%03d.png ~/.keras/datasets/lekf_I_dont_know.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_understand/lekf_I_dont_understand_%03d.png ~/.keras/datasets/lekf_I_dont_understand.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_negative/lekf_imagine_negative_%03d.png ~/.keras/datasets/lekf_imagine_negative.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_positive/lekf_imagine_positive_%03d.png ~/.keras/datasets/lekf_imagine_positive.mpg
ffmpeg -y -i ~/.keras/datasets/impressed/lekf_impressed_%03d.png ~/.keras/datasets/lekf_impressed.mpg
ffmpeg -y -i ~/.keras/datasets/insecurity/lekf_insecurity_%03d.png ~/.keras/datasets/lekf_insecurity.mpg
ffmpeg -y -i ~/.keras/datasets/not_convinced/lekf_not_convinced_%03d.png ~/.keras/datasets/lekf_not_convinced.mpg
ffmpeg -y -i ~/.keras/datasets/pain_felt/lekf_pain_felt_%03d.png ~/.keras/datasets/lekf_pain_felt.mpg
ffmpeg -y -i ~/.keras/datasets/pain_seen/lekf_pain_seen_%03d.png ~/.keras/datasets/lekf_pain_seen.mpg
ffmpeg -y -i ~/.keras/datasets/remember_negative/lekf_remember_negative_%03d.png ~/.keras/datasets/lekf_remember_negative.mpg
ffmpeg -y -i ~/.keras/datasets/remember_positive/lekf_remember_positive_%03d.png ~/.keras/datasets/lekf_remember_positive.mpg
ffmpeg -y -i ~/.keras/datasets/sad/lekf_sad_%03d.png ~/.keras/datasets/lekf_sad.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_encouraging/lekf_smiling_encouraging_%03d.png ~/.keras/datasets/lekf_smiling_encouraging.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_endearment/lekf_smiling_endearment_%03d.png ~/.keras/datasets/lekf_smiling_endearment.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_flirting/lekf_smiling_flirting_%03d.png ~/.keras/datasets/lekf_smiling_flirting.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sad-nostalgia/lekf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/lekf_smiling_sad-nostalgia.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sardonic/lekf_smiling_sardonic_%03d.png ~/.keras/datasets/lekf_smiling_sardonic.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_triumphant/lekf_smiling_triumphant_%03d.png ~/.keras/datasets/lekf_smiling_triumphant.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_uncertain/lekf_smiling_uncertain_%03d.png ~/.keras/datasets/lekf_smiling_uncertain.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_winning/lekf_smiling_winning_%03d.png ~/.keras/datasets/lekf_smiling_winning.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_yeah-right/lekf_smiling_yeah-right_%03d.png ~/.keras/datasets/lekf_smiling_yeah-right.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_considering/lekf_thinking_considering_%03d.png ~/.keras/datasets/lekf_thinking_considering.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_problem-solving/lekf_thinking_problem-solving_%03d.png ~/.keras/datasets/lekf_thinking_problem-solving.mpg
ffmpeg -y -i ~/.keras/datasets/tired/lekf_tired_%03d.png ~/.keras/datasets/lekf_tired.mpg
ffmpeg -y -i ~/.keras/datasets/treudoof_bambi-eyes/lekf_treudoof_bambi-eyes_%03d.png ~/.keras/datasets/lekf_treudoof_bambi-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/agree_considered/milf_agree_considered_%03d.png ~/.keras/datasets/milf_agree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/agree_continue/lekf_agree_continue_%03d.png ~/.keras/datasets/lekf_agree_continue.mpg
ffmpeg -y -i ~/.keras/datasets/agree_pure/lekf_agree_pure_%03d.png ~/.keras/datasets/lekf_agree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/agree_reluctant/lekf_agree_reluctant_%03d.png ~/.keras/datasets/lekf_agree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/aha-light_bulb_moment/lekf_aha-light_bulb_moment_%03d.png ~/.keras/datasets/lekf_aha-light_bulb_moment.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_bothered/lekf_annoyed_bothered_%03d.png ~/.keras/datasets/lekf_annoyed_bothered.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_rolling-eyes/lekf_annoyed_rolling-eyes_%03d.png ~/.keras/datasets/lekf_annoyed_rolling-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/arrogant/lekf_arrogant_%03d.png ~/.keras/datasets/lekf_arrogant.mpg
ffmpeg -y -i ~/.keras/datasets/bored/lekf_bored_%03d.png ~/.keras/datasets/lekf_bored.mpg
ffmpeg -y -i ~/.keras/datasets/compassion/lekf_compassion_%03d.png ~/.keras/datasets/lekf_compassion.mpg
ffmpeg -y -i ~/.keras/datasets/confused/lekf_confused_%03d.png ~/.keras/datasets/lekf_confused.mpg
ffmpeg -y -i ~/.keras/datasets/contempt/lekf_contempt_%03d.png ~/.keras/datasets/lekf_contempt.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_considered/lekf_disagree_considered_%03d.png ~/.keras/datasets/lekf_disagree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_pure/lekf_disagree_pure_%03d.png ~/.keras/datasets/lekf_disagree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_reluctant/lekf_disagree_reluctant_%03d.png ~/.keras/datasets/lekf_disagree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/disbelief/lekf_disbelief_%03d.png ~/.keras/datasets/lekf_disbelief.mpg
ffmpeg -y -i ~/.keras/datasets/disgust/lekf_disgust_%03d.png ~/.keras/datasets/lekf_disgust.mpg
ffmpeg -y -i ~/.keras/datasets/embarrassment/lekf_embarrassment_%03d.png ~/.keras/datasets/lekf_embarrassment.mpg
ffmpeg -y -i ~/.keras/datasets/fear_oops/lekf_fear_oops_%03d.png ~/.keras/datasets/lekf_fear_oops.mpg
ffmpeg -y -i ~/.keras/datasets/fear_terror/lekf_fear_terror_%03d.png ~/.keras/datasets/lekf_fear_terror.mpg
ffmpeg -y -i ~/.keras/datasets/happy_achievement/lekf_happy_achievement_%03d.png ~/.keras/datasets/lekf_happy_achievement.mpg
ffmpeg -y -i ~/.keras/datasets/happy_laughing/lekf_happy_laughing_%03d.png ~/.keras/datasets/lekf_happy_laughing.mpg
ffmpeg -y -i ~/.keras/datasets/happy_satiated/lekf_happy_satiated_%03d.png ~/.keras/datasets/lekf_happy_satiated.mpg
ffmpeg -y -i ~/.keras/datasets/happy_schadenfreude/lekf_happy_schadenfreude_%03d.png ~/.keras/datasets/lekf_happy_schadenfreude.mpg
ffmpeg -y -i ~/.keras/datasets/I_did_not_hear/lekf_I_did_not_hear_%03d.png ~/.keras/datasets/lekf_I_did_not_hear.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_care/lekf_I_dont_care_%03d.png ~/.keras/datasets/lekf_I_dont_care.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_know/lekf_I_dont_know_%03d.png ~/.keras/datasets/lekf_I_dont_know.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_understand/lekf_I_dont_understand_%03d.png ~/.keras/datasets/lekf_I_dont_understand.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_negative/lekf_imagine_negative_%03d.png ~/.keras/datasets/lekf_imagine_negative.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_positive/lekf_imagine_positive_%03d.png ~/.keras/datasets/lekf_imagine_positive.mpg
ffmpeg -y -i ~/.keras/datasets/impressed/lekf_impressed_%03d.png ~/.keras/datasets/lekf_impressed.mpg
ffmpeg -y -i ~/.keras/datasets/insecurity/lekf_insecurity_%03d.png ~/.keras/datasets/lekf_insecurity.mpg
ffmpeg -y -i ~/.keras/datasets/not_convinced/lekf_not_convinced_%03d.png ~/.keras/datasets/lekf_not_convinced.mpg
ffmpeg -y -i ~/.keras/datasets/pain_felt/lekf_pain_felt_%03d.png ~/.keras/datasets/lekf_pain_felt.mpg
ffmpeg -y -i ~/.keras/datasets/pain_seen/lekf_pain_seen_%03d.png ~/.keras/datasets/lekf_pain_seen.mpg
ffmpeg -y -i ~/.keras/datasets/remember_negative/lekf_remember_negative_%03d.png ~/.keras/datasets/lekf_remember_negative.mpg
ffmpeg -y -i ~/.keras/datasets/remember_positive/lekf_remember_positive_%03d.png ~/.keras/datasets/lekf_remember_positive.mpg
ffmpeg -y -i ~/.keras/datasets/sad/lekf_sad_%03d.png ~/.keras/datasets/lekf_sad.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_encouraging/lekf_smiling_encouraging_%03d.png ~/.keras/datasets/lekf_smiling_encouraging.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_endearment/lekf_smiling_endearment_%03d.png ~/.keras/datasets/lekf_smiling_endearment.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_flirting/lekf_smiling_flirting_%03d.png ~/.keras/datasets/lekf_smiling_flirting.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sad-nostalgia/lekf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/lekf_smiling_sad-nostalgia.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sardonic/lekf_smiling_sardonic_%03d.png ~/.keras/datasets/lekf_smiling_sardonic.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_triumphant/lekf_smiling_triumphant_%03d.png ~/.keras/datasets/lekf_smiling_triumphant.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_uncertain/lekf_smiling_uncertain_%03d.png ~/.keras/datasets/lekf_smiling_uncertain.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_winning/lekf_smiling_winning_%03d.png ~/.keras/datasets/lekf_smiling_winning.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_yeah-right/lekf_smiling_yeah-right_%03d.png ~/.keras/datasets/lekf_smiling_yeah-right.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_considering/lekf_thinking_considering_%03d.png ~/.keras/datasets/lekf_thinking_considering.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_problem-solving/lekf_thinking_problem-solving_%03d.png ~/.keras/datasets/lekf_thinking_problem-solving.mpg
ffmpeg -y -i ~/.keras/datasets/tired/lekf_tired_%03d.png ~/.keras/datasets/lekf_tired.mpg
ffmpeg -y -i ~/.keras/datasets/treudoof_bambi-eyes/lekf_treudoof_bambi-eyes_%03d.png ~/.keras/datasets/lekf_treudoof_bambi-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/agree_considered/silf_agree_considered_%03d.png ~/.keras/datasets/silf_agree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/agree_continue/lekf_agree_continue_%03d.png ~/.keras/datasets/lekf_agree_continue.mpg
ffmpeg -y -i ~/.keras/datasets/agree_pure/lekf_agree_pure_%03d.png ~/.keras/datasets/lekf_agree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/agree_reluctant/lekf_agree_reluctant_%03d.png ~/.keras/datasets/lekf_agree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/aha-light_bulb_moment/lekf_aha-light_bulb_moment_%03d.png ~/.keras/datasets/lekf_aha-light_bulb_moment.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_bothered/lekf_annoyed_bothered_%03d.png ~/.keras/datasets/lekf_annoyed_bothered.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_rolling-eyes/lekf_annoyed_rolling-eyes_%03d.png ~/.keras/datasets/lekf_annoyed_rolling-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/arrogant/lekf_arrogant_%03d.png ~/.keras/datasets/lekf_arrogant.mpg
ffmpeg -y -i ~/.keras/datasets/bored/lekf_bored_%03d.png ~/.keras/datasets/lekf_bored.mpg
ffmpeg -y -i ~/.keras/datasets/compassion/lekf_compassion_%03d.png ~/.keras/datasets/lekf_compassion.mpg
ffmpeg -y -i ~/.keras/datasets/confused/lekf_confused_%03d.png ~/.keras/datasets/lekf_confused.mpg
ffmpeg -y -i ~/.keras/datasets/contempt/lekf_contempt_%03d.png ~/.keras/datasets/lekf_contempt.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_considered/lekf_disagree_considered_%03d.png ~/.keras/datasets/lekf_disagree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_pure/lekf_disagree_pure_%03d.png ~/.keras/datasets/lekf_disagree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_reluctant/lekf_disagree_reluctant_%03d.png ~/.keras/datasets/lekf_disagree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/disbelief/lekf_disbelief_%03d.png ~/.keras/datasets/lekf_disbelief.mpg
ffmpeg -y -i ~/.keras/datasets/disgust/lekf_disgust_%03d.png ~/.keras/datasets/lekf_disgust.mpg
ffmpeg -y -i ~/.keras/datasets/embarrassment/lekf_embarrassment_%03d.png ~/.keras/datasets/lekf_embarrassment.mpg
ffmpeg -y -i ~/.keras/datasets/fear_oops/lekf_fear_oops_%03d.png ~/.keras/datasets/lekf_fear_oops.mpg
ffmpeg -y -i ~/.keras/datasets/fear_terror/lekf_fear_terror_%03d.png ~/.keras/datasets/lekf_fear_terror.mpg
ffmpeg -y -i ~/.keras/datasets/happy_achievement/lekf_happy_achievement_%03d.png ~/.keras/datasets/lekf_happy_achievement.mpg
ffmpeg -y -i ~/.keras/datasets/happy_laughing/lekf_happy_laughing_%03d.png ~/.keras/datasets/lekf_happy_laughing.mpg
ffmpeg -y -i ~/.keras/datasets/happy_satiated/lekf_happy_satiated_%03d.png ~/.keras/datasets/lekf_happy_satiated.mpg
ffmpeg -y -i ~/.keras/datasets/happy_schadenfreude/lekf_happy_schadenfreude_%03d.png ~/.keras/datasets/lekf_happy_schadenfreude.mpg
ffmpeg -y -i ~/.keras/datasets/I_did_not_hear/lekf_I_did_not_hear_%03d.png ~/.keras/datasets/lekf_I_did_not_hear.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_care/lekf_I_dont_care_%03d.png ~/.keras/datasets/lekf_I_dont_care.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_know/lekf_I_dont_know_%03d.png ~/.keras/datasets/lekf_I_dont_know.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_understand/lekf_I_dont_understand_%03d.png ~/.keras/datasets/lekf_I_dont_understand.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_negative/lekf_imagine_negative_%03d.png ~/.keras/datasets/lekf_imagine_negative.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_positive/lekf_imagine_positive_%03d.png ~/.keras/datasets/lekf_imagine_positive.mpg
ffmpeg -y -i ~/.keras/datasets/impressed/lekf_impressed_%03d.png ~/.keras/datasets/lekf_impressed.mpg
ffmpeg -y -i ~/.keras/datasets/insecurity/lekf_insecurity_%03d.png ~/.keras/datasets/lekf_insecurity.mpg
ffmpeg -y -i ~/.keras/datasets/not_convinced/lekf_not_convinced_%03d.png ~/.keras/datasets/lekf_not_convinced.mpg
ffmpeg -y -i ~/.keras/datasets/pain_felt/lekf_pain_felt_%03d.png ~/.keras/datasets/lekf_pain_felt.mpg
ffmpeg -y -i ~/.keras/datasets/pain_seen/lekf_pain_seen_%03d.png ~/.keras/datasets/lekf_pain_seen.mpg
ffmpeg -y -i ~/.keras/datasets/remember_negative/lekf_remember_negative_%03d.png ~/.keras/datasets/lekf_remember_negative.mpg
ffmpeg -y -i ~/.keras/datasets/remember_positive/lekf_remember_positive_%03d.png ~/.keras/datasets/lekf_remember_positive.mpg
ffmpeg -y -i ~/.keras/datasets/sad/lekf_sad_%03d.png ~/.keras/datasets/lekf_sad.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_encouraging/lekf_smiling_encouraging_%03d.png ~/.keras/datasets/lekf_smiling_encouraging.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_endearment/lekf_smiling_endearment_%03d.png ~/.keras/datasets/lekf_smiling_endearment.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_flirting/lekf_smiling_flirting_%03d.png ~/.keras/datasets/lekf_smiling_flirting.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sad-nostalgia/lekf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/lekf_smiling_sad-nostalgia.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sardonic/lekf_smiling_sardonic_%03d.png ~/.keras/datasets/lekf_smiling_sardonic.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_triumphant/lekf_smiling_triumphant_%03d.png ~/.keras/datasets/lekf_smiling_triumphant.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_uncertain/lekf_smiling_uncertain_%03d.png ~/.keras/datasets/lekf_smiling_uncertain.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_winning/lekf_smiling_winning_%03d.png ~/.keras/datasets/lekf_smiling_winning.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_yeah-right/lekf_smiling_yeah-right_%03d.png ~/.keras/datasets/lekf_smiling_yeah-right.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_considering/lekf_thinking_considering_%03d.png ~/.keras/datasets/lekf_thinking_considering.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_problem-solving/lekf_thinking_problem-solving_%03d.png ~/.keras/datasets/lekf_thinking_problem-solving.mpg
ffmpeg -y -i ~/.keras/datasets/tired/lekf_tired_%03d.png ~/.keras/datasets/lekf_tired.mpg
ffmpeg -y -i ~/.keras/datasets/treudoof_bambi-eyes/lekf_treudoof_bambi-eyes_%03d.png ~/.keras/datasets/lekf_treudoof_bambi-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/agree_considered/cawm_agree_considered_%03d.png ~/.keras/datasets/cawm_agree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/agree_continue/lekf_agree_continue_%03d.png ~/.keras/datasets/lekf_agree_continue.mpg
ffmpeg -y -i ~/.keras/datasets/agree_pure/lekf_agree_pure_%03d.png ~/.keras/datasets/lekf_agree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/agree_reluctant/lekf_agree_reluctant_%03d.png ~/.keras/datasets/lekf_agree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/aha-light_bulb_moment/lekf_aha-light_bulb_moment_%03d.png ~/.keras/datasets/lekf_aha-light_bulb_moment.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_bothered/lekf_annoyed_bothered_%03d.png ~/.keras/datasets/lekf_annoyed_bothered.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_rolling-eyes/lekf_annoyed_rolling-eyes_%03d.png ~/.keras/datasets/lekf_annoyed_rolling-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/arrogant/lekf_arrogant_%03d.png ~/.keras/datasets/lekf_arrogant.mpg
ffmpeg -y -i ~/.keras/datasets/bored/lekf_bored_%03d.png ~/.keras/datasets/lekf_bored.mpg
ffmpeg -y -i ~/.keras/datasets/compassion/lekf_compassion_%03d.png ~/.keras/datasets/lekf_compassion.mpg
ffmpeg -y -i ~/.keras/datasets/confused/lekf_confused_%03d.png ~/.keras/datasets/lekf_confused.mpg
ffmpeg -y -i ~/.keras/datasets/contempt/lekf_contempt_%03d.png ~/.keras/datasets/lekf_contempt.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_considered/lekf_disagree_considered_%03d.png ~/.keras/datasets/lekf_disagree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_pure/lekf_disagree_pure_%03d.png ~/.keras/datasets/lekf_disagree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_reluctant/lekf_disagree_reluctant_%03d.png ~/.keras/datasets/lekf_disagree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/disbelief/lekf_disbelief_%03d.png ~/.keras/datasets/lekf_disbelief.mpg
ffmpeg -y -i ~/.keras/datasets/disgust/lekf_disgust_%03d.png ~/.keras/datasets/lekf_disgust.mpg
ffmpeg -y -i ~/.keras/datasets/embarrassment/lekf_embarrassment_%03d.png ~/.keras/datasets/lekf_embarrassment.mpg
ffmpeg -y -i ~/.keras/datasets/fear_oops/lekf_fear_oops_%03d.png ~/.keras/datasets/lekf_fear_oops.mpg
ffmpeg -y -i ~/.keras/datasets/fear_terror/lekf_fear_terror_%03d.png ~/.keras/datasets/lekf_fear_terror.mpg
ffmpeg -y -i ~/.keras/datasets/happy_achievement/lekf_happy_achievement_%03d.png ~/.keras/datasets/lekf_happy_achievement.mpg
ffmpeg -y -i ~/.keras/datasets/happy_laughing/lekf_happy_laughing_%03d.png ~/.keras/datasets/lekf_happy_laughing.mpg
ffmpeg -y -i ~/.keras/datasets/happy_satiated/lekf_happy_satiated_%03d.png ~/.keras/datasets/lekf_happy_satiated.mpg
ffmpeg -y -i ~/.keras/datasets/happy_schadenfreude/lekf_happy_schadenfreude_%03d.png ~/.keras/datasets/lekf_happy_schadenfreude.mpg
ffmpeg -y -i ~/.keras/datasets/I_did_not_hear/lekf_I_did_not_hear_%03d.png ~/.keras/datasets/lekf_I_did_not_hear.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_care/lekf_I_dont_care_%03d.png ~/.keras/datasets/lekf_I_dont_care.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_know/lekf_I_dont_know_%03d.png ~/.keras/datasets/lekf_I_dont_know.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_understand/lekf_I_dont_understand_%03d.png ~/.keras/datasets/lekf_I_dont_understand.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_negative/lekf_imagine_negative_%03d.png ~/.keras/datasets/lekf_imagine_negative.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_positive/lekf_imagine_positive_%03d.png ~/.keras/datasets/lekf_imagine_positive.mpg
ffmpeg -y -i ~/.keras/datasets/impressed/lekf_impressed_%03d.png ~/.keras/datasets/lekf_impressed.mpg
ffmpeg -y -i ~/.keras/datasets/insecurity/lekf_insecurity_%03d.png ~/.keras/datasets/lekf_insecurity.mpg
ffmpeg -y -i ~/.keras/datasets/not_convinced/lekf_not_convinced_%03d.png ~/.keras/datasets/lekf_not_convinced.mpg
ffmpeg -y -i ~/.keras/datasets/pain_felt/lekf_pain_felt_%03d.png ~/.keras/datasets/lekf_pain_felt.mpg
ffmpeg -y -i ~/.keras/datasets/pain_seen/lekf_pain_seen_%03d.png ~/.keras/datasets/lekf_pain_seen.mpg
ffmpeg -y -i ~/.keras/datasets/remember_negative/lekf_remember_negative_%03d.png ~/.keras/datasets/lekf_remember_negative.mpg
ffmpeg -y -i ~/.keras/datasets/remember_positive/lekf_remember_positive_%03d.png ~/.keras/datasets/lekf_remember_positive.mpg
ffmpeg -y -i ~/.keras/datasets/sad/lekf_sad_%03d.png ~/.keras/datasets/lekf_sad.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_encouraging/lekf_smiling_encouraging_%03d.png ~/.keras/datasets/lekf_smiling_encouraging.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_endearment/lekf_smiling_endearment_%03d.png ~/.keras/datasets/lekf_smiling_endearment.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_flirting/lekf_smiling_flirting_%03d.png ~/.keras/datasets/lekf_smiling_flirting.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sad-nostalgia/lekf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/lekf_smiling_sad-nostalgia.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sardonic/lekf_smiling_sardonic_%03d.png ~/.keras/datasets/lekf_smiling_sardonic.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_triumphant/lekf_smiling_triumphant_%03d.png ~/.keras/datasets/lekf_smiling_triumphant.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_uncertain/lekf_smiling_uncertain_%03d.png ~/.keras/datasets/lekf_smiling_uncertain.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_winning/lekf_smiling_winning_%03d.png ~/.keras/datasets/lekf_smiling_winning.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_yeah-right/lekf_smiling_yeah-right_%03d.png ~/.keras/datasets/lekf_smiling_yeah-right.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_considering/lekf_thinking_considering_%03d.png ~/.keras/datasets/lekf_thinking_considering.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_problem-solving/lekf_thinking_problem-solving_%03d.png ~/.keras/datasets/lekf_thinking_problem-solving.mpg
ffmpeg -y -i ~/.keras/datasets/tired/lekf_tired_%03d.png ~/.keras/datasets/lekf_tired.mpg
ffmpeg -y -i ~/.keras/datasets/treudoof_bambi-eyes/lekf_treudoof_bambi-eyes_%03d.png ~/.keras/datasets/lekf_treudoof_bambi-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/agree_considered/chsm_agree_considered_%03d.png ~/.keras/datasets/chsm_agree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/agree_continue/lekf_agree_continue_%03d.png ~/.keras/datasets/lekf_agree_continue.mpg
ffmpeg -y -i ~/.keras/datasets/agree_pure/lekf_agree_pure_%03d.png ~/.keras/datasets/lekf_agree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/agree_reluctant/lekf_agree_reluctant_%03d.png ~/.keras/datasets/lekf_agree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/aha-light_bulb_moment/lekf_aha-light_bulb_moment_%03d.png ~/.keras/datasets/lekf_aha-light_bulb_moment.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_bothered/lekf_annoyed_bothered_%03d.png ~/.keras/datasets/lekf_annoyed_bothered.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_rolling-eyes/lekf_annoyed_rolling-eyes_%03d.png ~/.keras/datasets/lekf_annoyed_rolling-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/arrogant/lekf_arrogant_%03d.png ~/.keras/datasets/lekf_arrogant.mpg
ffmpeg -y -i ~/.keras/datasets/bored/lekf_bored_%03d.png ~/.keras/datasets/lekf_bored.mpg
ffmpeg -y -i ~/.keras/datasets/compassion/lekf_compassion_%03d.png ~/.keras/datasets/lekf_compassion.mpg
ffmpeg -y -i ~/.keras/datasets/confused/lekf_confused_%03d.png ~/.keras/datasets/lekf_confused.mpg
ffmpeg -y -i ~/.keras/datasets/contempt/lekf_contempt_%03d.png ~/.keras/datasets/lekf_contempt.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_considered/lekf_disagree_considered_%03d.png ~/.keras/datasets/lekf_disagree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_pure/lekf_disagree_pure_%03d.png ~/.keras/datasets/lekf_disagree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_reluctant/lekf_disagree_reluctant_%03d.png ~/.keras/datasets/lekf_disagree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/disbelief/lekf_disbelief_%03d.png ~/.keras/datasets/lekf_disbelief.mpg
ffmpeg -y -i ~/.keras/datasets/disgust/lekf_disgust_%03d.png ~/.keras/datasets/lekf_disgust.mpg
ffmpeg -y -i ~/.keras/datasets/embarrassment/lekf_embarrassment_%03d.png ~/.keras/datasets/lekf_embarrassment.mpg
ffmpeg -y -i ~/.keras/datasets/fear_oops/lekf_fear_oops_%03d.png ~/.keras/datasets/lekf_fear_oops.mpg
ffmpeg -y -i ~/.keras/datasets/fear_terror/lekf_fear_terror_%03d.png ~/.keras/datasets/lekf_fear_terror.mpg
ffmpeg -y -i ~/.keras/datasets/happy_achievement/lekf_happy_achievement_%03d.png ~/.keras/datasets/lekf_happy_achievement.mpg
ffmpeg -y -i ~/.keras/datasets/happy_laughing/lekf_happy_laughing_%03d.png ~/.keras/datasets/lekf_happy_laughing.mpg
ffmpeg -y -i ~/.keras/datasets/happy_satiated/lekf_happy_satiated_%03d.png ~/.keras/datasets/lekf_happy_satiated.mpg
ffmpeg -y -i ~/.keras/datasets/happy_schadenfreude/lekf_happy_schadenfreude_%03d.png ~/.keras/datasets/lekf_happy_schadenfreude.mpg
ffmpeg -y -i ~/.keras/datasets/I_did_not_hear/lekf_I_did_not_hear_%03d.png ~/.keras/datasets/lekf_I_did_not_hear.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_care/lekf_I_dont_care_%03d.png ~/.keras/datasets/lekf_I_dont_care.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_know/lekf_I_dont_know_%03d.png ~/.keras/datasets/lekf_I_dont_know.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_understand/lekf_I_dont_understand_%03d.png ~/.keras/datasets/lekf_I_dont_understand.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_negative/lekf_imagine_negative_%03d.png ~/.keras/datasets/lekf_imagine_negative.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_positive/lekf_imagine_positive_%03d.png ~/.keras/datasets/lekf_imagine_positive.mpg
ffmpeg -y -i ~/.keras/datasets/impressed/lekf_impressed_%03d.png ~/.keras/datasets/lekf_impressed.mpg
ffmpeg -y -i ~/.keras/datasets/insecurity/lekf_insecurity_%03d.png ~/.keras/datasets/lekf_insecurity.mpg
ffmpeg -y -i ~/.keras/datasets/not_convinced/lekf_not_convinced_%03d.png ~/.keras/datasets/lekf_not_convinced.mpg
ffmpeg -y -i ~/.keras/datasets/pain_felt/lekf_pain_felt_%03d.png ~/.keras/datasets/lekf_pain_felt.mpg
ffmpeg -y -i ~/.keras/datasets/pain_seen/lekf_pain_seen_%03d.png ~/.keras/datasets/lekf_pain_seen.mpg
ffmpeg -y -i ~/.keras/datasets/remember_negative/lekf_remember_negative_%03d.png ~/.keras/datasets/lekf_remember_negative.mpg
ffmpeg -y -i ~/.keras/datasets/remember_positive/lekf_remember_positive_%03d.png ~/.keras/datasets/lekf_remember_positive.mpg
ffmpeg -y -i ~/.keras/datasets/sad/lekf_sad_%03d.png ~/.keras/datasets/lekf_sad.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_encouraging/lekf_smiling_encouraging_%03d.png ~/.keras/datasets/lekf_smiling_encouraging.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_endearment/lekf_smiling_endearment_%03d.png ~/.keras/datasets/lekf_smiling_endearment.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_flirting/lekf_smiling_flirting_%03d.png ~/.keras/datasets/lekf_smiling_flirting.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sad-nostalgia/lekf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/lekf_smiling_sad-nostalgia.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sardonic/lekf_smiling_sardonic_%03d.png ~/.keras/datasets/lekf_smiling_sardonic.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_triumphant/lekf_smiling_triumphant_%03d.png ~/.keras/datasets/lekf_smiling_triumphant.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_uncertain/lekf_smiling_uncertain_%03d.png ~/.keras/datasets/lekf_smiling_uncertain.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_winning/lekf_smiling_winning_%03d.png ~/.keras/datasets/lekf_smiling_winning.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_yeah-right/lekf_smiling_yeah-right_%03d.png ~/.keras/datasets/lekf_smiling_yeah-right.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_considering/lekf_thinking_considering_%03d.png ~/.keras/datasets/lekf_thinking_considering.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_problem-solving/lekf_thinking_problem-solving_%03d.png ~/.keras/datasets/lekf_thinking_problem-solving.mpg
ffmpeg -y -i ~/.keras/datasets/tired/lekf_tired_%03d.png ~/.keras/datasets/lekf_tired.mpg
ffmpeg -y -i ~/.keras/datasets/treudoof_bambi-eyes/lekf_treudoof_bambi-eyes_%03d.png ~/.keras/datasets/lekf_treudoof_bambi-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/agree_considered/jakm_agree_considered_%03d.png ~/.keras/datasets/jakm_agree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/agree_continue/lekf_agree_continue_%03d.png ~/.keras/datasets/lekf_agree_continue.mpg
ffmpeg -y -i ~/.keras/datasets/agree_pure/lekf_agree_pure_%03d.png ~/.keras/datasets/lekf_agree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/agree_reluctant/lekf_agree_reluctant_%03d.png ~/.keras/datasets/lekf_agree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/aha-light_bulb_moment/lekf_aha-light_bulb_moment_%03d.png ~/.keras/datasets/lekf_aha-light_bulb_moment.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_bothered/lekf_annoyed_bothered_%03d.png ~/.keras/datasets/lekf_annoyed_bothered.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_rolling-eyes/lekf_annoyed_rolling-eyes_%03d.png ~/.keras/datasets/lekf_annoyed_rolling-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/arrogant/lekf_arrogant_%03d.png ~/.keras/datasets/lekf_arrogant.mpg
ffmpeg -y -i ~/.keras/datasets/bored/lekf_bored_%03d.png ~/.keras/datasets/lekf_bored.mpg
ffmpeg -y -i ~/.keras/datasets/compassion/lekf_compassion_%03d.png ~/.keras/datasets/lekf_compassion.mpg
ffmpeg -y -i ~/.keras/datasets/confused/lekf_confused_%03d.png ~/.keras/datasets/lekf_confused.mpg
ffmpeg -y -i ~/.keras/datasets/contempt/lekf_contempt_%03d.png ~/.keras/datasets/lekf_contempt.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_considered/lekf_disagree_considered_%03d.png ~/.keras/datasets/lekf_disagree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_pure/lekf_disagree_pure_%03d.png ~/.keras/datasets/lekf_disagree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_reluctant/lekf_disagree_reluctant_%03d.png ~/.keras/datasets/lekf_disagree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/disbelief/lekf_disbelief_%03d.png ~/.keras/datasets/lekf_disbelief.mpg
ffmpeg -y -i ~/.keras/datasets/disgust/lekf_disgust_%03d.png ~/.keras/datasets/lekf_disgust.mpg
ffmpeg -y -i ~/.keras/datasets/embarrassment/lekf_embarrassment_%03d.png ~/.keras/datasets/lekf_embarrassment.mpg
ffmpeg -y -i ~/.keras/datasets/fear_oops/lekf_fear_oops_%03d.png ~/.keras/datasets/lekf_fear_oops.mpg
ffmpeg -y -i ~/.keras/datasets/fear_terror/lekf_fear_terror_%03d.png ~/.keras/datasets/lekf_fear_terror.mpg
ffmpeg -y -i ~/.keras/datasets/happy_achievement/lekf_happy_achievement_%03d.png ~/.keras/datasets/lekf_happy_achievement.mpg
ffmpeg -y -i ~/.keras/datasets/happy_laughing/lekf_happy_laughing_%03d.png ~/.keras/datasets/lekf_happy_laughing.mpg
ffmpeg -y -i ~/.keras/datasets/happy_satiated/lekf_happy_satiated_%03d.png ~/.keras/datasets/lekf_happy_satiated.mpg
ffmpeg -y -i ~/.keras/datasets/happy_schadenfreude/lekf_happy_schadenfreude_%03d.png ~/.keras/datasets/lekf_happy_schadenfreude.mpg
ffmpeg -y -i ~/.keras/datasets/I_did_not_hear/lekf_I_did_not_hear_%03d.png ~/.keras/datasets/lekf_I_did_not_hear.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_care/lekf_I_dont_care_%03d.png ~/.keras/datasets/lekf_I_dont_care.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_know/lekf_I_dont_know_%03d.png ~/.keras/datasets/lekf_I_dont_know.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_understand/lekf_I_dont_understand_%03d.png ~/.keras/datasets/lekf_I_dont_understand.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_negative/lekf_imagine_negative_%03d.png ~/.keras/datasets/lekf_imagine_negative.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_positive/lekf_imagine_positive_%03d.png ~/.keras/datasets/lekf_imagine_positive.mpg
ffmpeg -y -i ~/.keras/datasets/impressed/lekf_impressed_%03d.png ~/.keras/datasets/lekf_impressed.mpg
ffmpeg -y -i ~/.keras/datasets/insecurity/lekf_insecurity_%03d.png ~/.keras/datasets/lekf_insecurity.mpg
ffmpeg -y -i ~/.keras/datasets/not_convinced/lekf_not_convinced_%03d.png ~/.keras/datasets/lekf_not_convinced.mpg
ffmpeg -y -i ~/.keras/datasets/pain_felt/lekf_pain_felt_%03d.png ~/.keras/datasets/lekf_pain_felt.mpg
ffmpeg -y -i ~/.keras/datasets/pain_seen/lekf_pain_seen_%03d.png ~/.keras/datasets/lekf_pain_seen.mpg
ffmpeg -y -i ~/.keras/datasets/remember_negative/lekf_remember_negative_%03d.png ~/.keras/datasets/lekf_remember_negative.mpg
ffmpeg -y -i ~/.keras/datasets/remember_positive/lekf_remember_positive_%03d.png ~/.keras/datasets/lekf_remember_positive.mpg
ffmpeg -y -i ~/.keras/datasets/sad/lekf_sad_%03d.png ~/.keras/datasets/lekf_sad.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_encouraging/lekf_smiling_encouraging_%03d.png ~/.keras/datasets/lekf_smiling_encouraging.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_endearment/lekf_smiling_endearment_%03d.png ~/.keras/datasets/lekf_smiling_endearment.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_flirting/lekf_smiling_flirting_%03d.png ~/.keras/datasets/lekf_smiling_flirting.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sad-nostalgia/lekf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/lekf_smiling_sad-nostalgia.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sardonic/lekf_smiling_sardonic_%03d.png ~/.keras/datasets/lekf_smiling_sardonic.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_triumphant/lekf_smiling_triumphant_%03d.png ~/.keras/datasets/lekf_smiling_triumphant.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_uncertain/lekf_smiling_uncertain_%03d.png ~/.keras/datasets/lekf_smiling_uncertain.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_winning/lekf_smiling_winning_%03d.png ~/.keras/datasets/lekf_smiling_winning.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_yeah-right/lekf_smiling_yeah-right_%03d.png ~/.keras/datasets/lekf_smiling_yeah-right.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_considering/lekf_thinking_considering_%03d.png ~/.keras/datasets/lekf_thinking_considering.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_problem-solving/lekf_thinking_problem-solving_%03d.png ~/.keras/datasets/lekf_thinking_problem-solving.mpg
ffmpeg -y -i ~/.keras/datasets/tired/lekf_tired_%03d.png ~/.keras/datasets/lekf_tired.mpg
ffmpeg -y -i ~/.keras/datasets/treudoof_bambi-eyes/lekf_treudoof_bambi-eyes_%03d.png ~/.keras/datasets/lekf_treudoof_bambi-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/agree_considered/juhm_agree_considered_%03d.png ~/.keras/datasets/juhm_agree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/agree_continue/lekf_agree_continue_%03d.png ~/.keras/datasets/lekf_agree_continue.mpg
ffmpeg -y -i ~/.keras/datasets/agree_pure/lekf_agree_pure_%03d.png ~/.keras/datasets/lekf_agree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/agree_reluctant/lekf_agree_reluctant_%03d.png ~/.keras/datasets/lekf_agree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/aha-light_bulb_moment/lekf_aha-light_bulb_moment_%03d.png ~/.keras/datasets/lekf_aha-light_bulb_moment.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_bothered/lekf_annoyed_bothered_%03d.png ~/.keras/datasets/lekf_annoyed_bothered.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_rolling-eyes/lekf_annoyed_rolling-eyes_%03d.png ~/.keras/datasets/lekf_annoyed_rolling-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/arrogant/lekf_arrogant_%03d.png ~/.keras/datasets/lekf_arrogant.mpg
ffmpeg -y -i ~/.keras/datasets/bored/lekf_bored_%03d.png ~/.keras/datasets/lekf_bored.mpg
ffmpeg -y -i ~/.keras/datasets/compassion/lekf_compassion_%03d.png ~/.keras/datasets/lekf_compassion.mpg
ffmpeg -y -i ~/.keras/datasets/confused/lekf_confused_%03d.png ~/.keras/datasets/lekf_confused.mpg
ffmpeg -y -i ~/.keras/datasets/contempt/lekf_contempt_%03d.png ~/.keras/datasets/lekf_contempt.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_considered/lekf_disagree_considered_%03d.png ~/.keras/datasets/lekf_disagree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_pure/lekf_disagree_pure_%03d.png ~/.keras/datasets/lekf_disagree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_reluctant/lekf_disagree_reluctant_%03d.png ~/.keras/datasets/lekf_disagree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/disbelief/lekf_disbelief_%03d.png ~/.keras/datasets/lekf_disbelief.mpg
ffmpeg -y -i ~/.keras/datasets/disgust/lekf_disgust_%03d.png ~/.keras/datasets/lekf_disgust.mpg
ffmpeg -y -i ~/.keras/datasets/embarrassment/lekf_embarrassment_%03d.png ~/.keras/datasets/lekf_embarrassment.mpg
ffmpeg -y -i ~/.keras/datasets/fear_oops/lekf_fear_oops_%03d.png ~/.keras/datasets/lekf_fear_oops.mpg
ffmpeg -y -i ~/.keras/datasets/fear_terror/lekf_fear_terror_%03d.png ~/.keras/datasets/lekf_fear_terror.mpg
ffmpeg -y -i ~/.keras/datasets/happy_achievement/lekf_happy_achievement_%03d.png ~/.keras/datasets/lekf_happy_achievement.mpg
ffmpeg -y -i ~/.keras/datasets/happy_laughing/lekf_happy_laughing_%03d.png ~/.keras/datasets/lekf_happy_laughing.mpg
ffmpeg -y -i ~/.keras/datasets/happy_satiated/lekf_happy_satiated_%03d.png ~/.keras/datasets/lekf_happy_satiated.mpg
ffmpeg -y -i ~/.keras/datasets/happy_schadenfreude/lekf_happy_schadenfreude_%03d.png ~/.keras/datasets/lekf_happy_schadenfreude.mpg
ffmpeg -y -i ~/.keras/datasets/I_did_not_hear/lekf_I_did_not_hear_%03d.png ~/.keras/datasets/lekf_I_did_not_hear.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_care/lekf_I_dont_care_%03d.png ~/.keras/datasets/lekf_I_dont_care.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_know/lekf_I_dont_know_%03d.png ~/.keras/datasets/lekf_I_dont_know.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_understand/lekf_I_dont_understand_%03d.png ~/.keras/datasets/lekf_I_dont_understand.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_negative/lekf_imagine_negative_%03d.png ~/.keras/datasets/lekf_imagine_negative.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_positive/lekf_imagine_positive_%03d.png ~/.keras/datasets/lekf_imagine_positive.mpg
ffmpeg -y -i ~/.keras/datasets/impressed/lekf_impressed_%03d.png ~/.keras/datasets/lekf_impressed.mpg
ffmpeg -y -i ~/.keras/datasets/insecurity/lekf_insecurity_%03d.png ~/.keras/datasets/lekf_insecurity.mpg
ffmpeg -y -i ~/.keras/datasets/not_convinced/lekf_not_convinced_%03d.png ~/.keras/datasets/lekf_not_convinced.mpg
ffmpeg -y -i ~/.keras/datasets/pain_felt/lekf_pain_felt_%03d.png ~/.keras/datasets/lekf_pain_felt.mpg
ffmpeg -y -i ~/.keras/datasets/pain_seen/lekf_pain_seen_%03d.png ~/.keras/datasets/lekf_pain_seen.mpg
ffmpeg -y -i ~/.keras/datasets/remember_negative/lekf_remember_negative_%03d.png ~/.keras/datasets/lekf_remember_negative.mpg
ffmpeg -y -i ~/.keras/datasets/remember_positive/lekf_remember_positive_%03d.png ~/.keras/datasets/lekf_remember_positive.mpg
ffmpeg -y -i ~/.keras/datasets/sad/lekf_sad_%03d.png ~/.keras/datasets/lekf_sad.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_encouraging/lekf_smiling_encouraging_%03d.png ~/.keras/datasets/lekf_smiling_encouraging.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_endearment/lekf_smiling_endearment_%03d.png ~/.keras/datasets/lekf_smiling_endearment.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_flirting/lekf_smiling_flirting_%03d.png ~/.keras/datasets/lekf_smiling_flirting.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sad-nostalgia/lekf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/lekf_smiling_sad-nostalgia.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sardonic/lekf_smiling_sardonic_%03d.png ~/.keras/datasets/lekf_smiling_sardonic.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_triumphant/lekf_smiling_triumphant_%03d.png ~/.keras/datasets/lekf_smiling_triumphant.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_uncertain/lekf_smiling_uncertain_%03d.png ~/.keras/datasets/lekf_smiling_uncertain.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_winning/lekf_smiling_winning_%03d.png ~/.keras/datasets/lekf_smiling_winning.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_yeah-right/lekf_smiling_yeah-right_%03d.png ~/.keras/datasets/lekf_smiling_yeah-right.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_considering/lekf_thinking_considering_%03d.png ~/.keras/datasets/lekf_thinking_considering.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_problem-solving/lekf_thinking_problem-solving_%03d.png ~/.keras/datasets/lekf_thinking_problem-solving.mpg
ffmpeg -y -i ~/.keras/datasets/tired/lekf_tired_%03d.png ~/.keras/datasets/lekf_tired.mpg
ffmpeg -y -i ~/.keras/datasets/treudoof_bambi-eyes/lekf_treudoof_bambi-eyes_%03d.png ~/.keras/datasets/lekf_treudoof_bambi-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/agree_considered/mamm_agree_considered_%03d.png ~/.keras/datasets/mamm_agree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/agree_continue/lekf_agree_continue_%03d.png ~/.keras/datasets/lekf_agree_continue.mpg
ffmpeg -y -i ~/.keras/datasets/agree_pure/lekf_agree_pure_%03d.png ~/.keras/datasets/lekf_agree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/agree_reluctant/lekf_agree_reluctant_%03d.png ~/.keras/datasets/lekf_agree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/aha-light_bulb_moment/lekf_aha-light_bulb_moment_%03d.png ~/.keras/datasets/lekf_aha-light_bulb_moment.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_bothered/lekf_annoyed_bothered_%03d.png ~/.keras/datasets/lekf_annoyed_bothered.mpg
ffmpeg -y -i ~/.keras/datasets/annoyed_rolling-eyes/lekf_annoyed_rolling-eyes_%03d.png ~/.keras/datasets/lekf_annoyed_rolling-eyes.mpg
ffmpeg -y -i ~/.keras/datasets/arrogant/lekf_arrogant_%03d.png ~/.keras/datasets/lekf_arrogant.mpg
ffmpeg -y -i ~/.keras/datasets/bored/lekf_bored_%03d.png ~/.keras/datasets/lekf_bored.mpg
ffmpeg -y -i ~/.keras/datasets/compassion/lekf_compassion_%03d.png ~/.keras/datasets/lekf_compassion.mpg
ffmpeg -y -i ~/.keras/datasets/confused/lekf_confused_%03d.png ~/.keras/datasets/lekf_confused.mpg
ffmpeg -y -i ~/.keras/datasets/contempt/lekf_contempt_%03d.png ~/.keras/datasets/lekf_contempt.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_considered/lekf_disagree_considered_%03d.png ~/.keras/datasets/lekf_disagree_considered.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_pure/lekf_disagree_pure_%03d.png ~/.keras/datasets/lekf_disagree_pure.mpg
ffmpeg -y -i ~/.keras/datasets/disagree_reluctant/lekf_disagree_reluctant_%03d.png ~/.keras/datasets/lekf_disagree_reluctant.mpg
ffmpeg -y -i ~/.keras/datasets/disbelief/lekf_disbelief_%03d.png ~/.keras/datasets/lekf_disbelief.mpg
ffmpeg -y -i ~/.keras/datasets/disgust/lekf_disgust_%03d.png ~/.keras/datasets/lekf_disgust.mpg
ffmpeg -y -i ~/.keras/datasets/embarrassment/lekf_embarrassment_%03d.png ~/.keras/datasets/lekf_embarrassment.mpg
ffmpeg -y -i ~/.keras/datasets/fear_oops/lekf_fear_oops_%03d.png ~/.keras/datasets/lekf_fear_oops.mpg
ffmpeg -y -i ~/.keras/datasets/fear_terror/lekf_fear_terror_%03d.png ~/.keras/datasets/lekf_fear_terror.mpg
ffmpeg -y -i ~/.keras/datasets/happy_achievement/lekf_happy_achievement_%03d.png ~/.keras/datasets/lekf_happy_achievement.mpg
ffmpeg -y -i ~/.keras/datasets/happy_laughing/lekf_happy_laughing_%03d.png ~/.keras/datasets/lekf_happy_laughing.mpg
ffmpeg -y -i ~/.keras/datasets/happy_satiated/lekf_happy_satiated_%03d.png ~/.keras/datasets/lekf_happy_satiated.mpg
ffmpeg -y -i ~/.keras/datasets/happy_schadenfreude/lekf_happy_schadenfreude_%03d.png ~/.keras/datasets/lekf_happy_schadenfreude.mpg
ffmpeg -y -i ~/.keras/datasets/I_did_not_hear/lekf_I_did_not_hear_%03d.png ~/.keras/datasets/lekf_I_did_not_hear.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_care/lekf_I_dont_care_%03d.png ~/.keras/datasets/lekf_I_dont_care.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_know/lekf_I_dont_know_%03d.png ~/.keras/datasets/lekf_I_dont_know.mpg
ffmpeg -y -i ~/.keras/datasets/I_dont_understand/lekf_I_dont_understand_%03d.png ~/.keras/datasets/lekf_I_dont_understand.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_negative/lekf_imagine_negative_%03d.png ~/.keras/datasets/lekf_imagine_negative.mpg
ffmpeg -y -i ~/.keras/datasets/imagine_positive/lekf_imagine_positive_%03d.png ~/.keras/datasets/lekf_imagine_positive.mpg
ffmpeg -y -i ~/.keras/datasets/impressed/lekf_impressed_%03d.png ~/.keras/datasets/lekf_impressed.mpg
ffmpeg -y -i ~/.keras/datasets/insecurity/lekf_insecurity_%03d.png ~/.keras/datasets/lekf_insecurity.mpg
ffmpeg -y -i ~/.keras/datasets/not_convinced/lekf_not_convinced_%03d.png ~/.keras/datasets/lekf_not_convinced.mpg
ffmpeg -y -i ~/.keras/datasets/pain_felt/lekf_pain_felt_%03d.png ~/.keras/datasets/lekf_pain_felt.mpg
ffmpeg -y -i ~/.keras/datasets/pain_seen/lekf_pain_seen_%03d.png ~/.keras/datasets/lekf_pain_seen.mpg
ffmpeg -y -i ~/.keras/datasets/remember_negative/lekf_remember_negative_%03d.png ~/.keras/datasets/lekf_remember_negative.mpg
ffmpeg -y -i ~/.keras/datasets/remember_positive/lekf_remember_positive_%03d.png ~/.keras/datasets/lekf_remember_positive.mpg
ffmpeg -y -i ~/.keras/datasets/sad/lekf_sad_%03d.png ~/.keras/datasets/lekf_sad.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_encouraging/lekf_smiling_encouraging_%03d.png ~/.keras/datasets/lekf_smiling_encouraging.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_endearment/lekf_smiling_endearment_%03d.png ~/.keras/datasets/lekf_smiling_endearment.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_flirting/lekf_smiling_flirting_%03d.png ~/.keras/datasets/lekf_smiling_flirting.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sad-nostalgia/lekf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/lekf_smiling_sad-nostalgia.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_sardonic/lekf_smiling_sardonic_%03d.png ~/.keras/datasets/lekf_smiling_sardonic.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_triumphant/lekf_smiling_triumphant_%03d.png ~/.keras/datasets/lekf_smiling_triumphant.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_uncertain/lekf_smiling_uncertain_%03d.png ~/.keras/datasets/lekf_smiling_uncertain.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_winning/lekf_smiling_winning_%03d.png ~/.keras/datasets/lekf_smiling_winning.mpg
ffmpeg -y -i ~/.keras/datasets/smiling_yeah-right/lekf_smiling_yeah-right_%03d.png ~/.keras/datasets/lekf_smiling_yeah-right.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_considering/lekf_thinking_considering_%03d.png ~/.keras/datasets/lekf_thinking_considering.mpg
ffmpeg -y -i ~/.keras/datasets/thinking_problem-solving/lekf_thinking_problem-solving_%03d.png ~/.keras/datasets/lekf_thinking_problem-solving.mpg
ffmpeg -y -i ~/.keras/datasets/tired/lekf_tired_%03d.png ~/.keras/datasets/lekf_tired.mpg
ffmpeg -y -i ~/.keras/datasets/treudoof_bambi-eyes/lekf_treudoof_bambi-eyes_%03d.png ~/.keras/datasets/lekf_treudoof_bambi-eyes.mpg
