#!/bash/sh

mkdir ~/.keras/datasets/cec-videos
mkdir ~/.keras/datasets/cec-videos/agree_considered
mkdir ~/.keras/datasets/cec-videos/agree_continue
mkdir ~/.keras/datasets/cec-videos/agree_pure
mkdir ~/.keras/datasets/cec-videos/agree_reluctant
mkdir ~/.keras/datasets/cec-videos/aha-light_bulb_moment
mkdir ~/.keras/datasets/cec-videos/annoyed_bothered
mkdir ~/.keras/datasets/cec-videos/annoyed_rolling-eyes
mkdir ~/.keras/datasets/cec-videos/arrogant
mkdir ~/.keras/datasets/cec-videos/bored
mkdir ~/.keras/datasets/cec-videos/compassion
mkdir ~/.keras/datasets/cec-videos/confused
mkdir ~/.keras/datasets/cec-videos/contempt
mkdir ~/.keras/datasets/cec-videos/disagree_considered
mkdir ~/.keras/datasets/cec-videos/disagree_pure
mkdir ~/.keras/datasets/cec-videos/disagree_reluctant
mkdir ~/.keras/datasets/cec-videos/disbelief
mkdir ~/.keras/datasets/cec-videos/disgust
mkdir ~/.keras/datasets/cec-videos/embarrassment
mkdir ~/.keras/datasets/cec-videos/fear_oops
mkdir ~/.keras/datasets/cec-videos/fear_terror
mkdir ~/.keras/datasets/cec-videos/happy_achievement
mkdir ~/.keras/datasets/cec-videos/happy_laughing
mkdir ~/.keras/datasets/cec-videos/happy_satiated
mkdir ~/.keras/datasets/cec-videos/happy_schadenfreude
mkdir ~/.keras/datasets/cec-videos/I_did_not_hear
mkdir ~/.keras/datasets/cec-videos/I_dont_care
mkdir ~/.keras/datasets/cec-videos/I_dont_know
mkdir ~/.keras/datasets/cec-videos/I_dont_understand
mkdir ~/.keras/datasets/cec-videos/imagine_negative
mkdir ~/.keras/datasets/cec-videos/imagine_positive
mkdir ~/.keras/datasets/cec-videos/impressed
mkdir ~/.keras/datasets/cec-videos/insecurity
mkdir ~/.keras/datasets/cec-videos/not_convinced
mkdir ~/.keras/datasets/cec-videos/pain_felt
mkdir ~/.keras/datasets/cec-videos/pain_seen
mkdir ~/.keras/datasets/cec-videos/remember_negative
mkdir ~/.keras/datasets/cec-videos/remember_positive
mkdir ~/.keras/datasets/cec-videos/sad
mkdir ~/.keras/datasets/cec-videos/smiling_encouraging
mkdir ~/.keras/datasets/cec-videos/smiling_endearment
mkdir ~/.keras/datasets/cec-videos/smiling_flirting
mkdir ~/.keras/datasets/cec-videos/smiling_sad-nostalgia
mkdir ~/.keras/datasets/cec-videos/smiling_sardonic
mkdir ~/.keras/datasets/cec-videos/smiling_triumphant
mkdir ~/.keras/datasets/cec-videos/smiling_uncertain
mkdir ~/.keras/datasets/cec-videos/smiling_winning
mkdir ~/.keras/datasets/cec-videos/smiling_yeah-right
mkdir ~/.keras/datasets/cec-videos/thinking_considering
mkdir ~/.keras/datasets/cec-videos/thinking_problem-solving
mkdir ~/.keras/datasets/cec-videos/tired
mkdir ~/.keras/datasets/cec-videos/treudoof_bambi-eyes

ffmpeg -y -i ~/.keras/large-mpi-db/agree_considered/islf_agree_considered_%03d.png ~/.keras/datasets/cec-videos/agree_considered/islf_agree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_considered/kabf_agree_considered_%03d.png ~/.keras/datasets/cec-videos/agree_considered/kabf_agree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_considered/lekf_agree_considered_%03d.png ~/.keras/datasets/cec-videos/agree_considered/lekf_agree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_considered/milf_agree_considered_%03d.png ~/.keras/datasets/cec-videos/agree_considered/milf_agree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_considered/silf_agree_considered_%03d.png ~/.keras/datasets/cec-videos/agree_considered/silf_agree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_considered/cawm_agree_considered_%03d.png ~/.keras/datasets/cec-videos/agree_considered/cawm_agree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_considered/chsm_agree_considered_%03d.png ~/.keras/datasets/cec-videos/agree_considered/chsm_agree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_considered/jakm_agree_considered_%03d.png ~/.keras/datasets/cec-videos/agree_considered/jakm_agree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_considered/juhm_agree_considered_%03d.png ~/.keras/datasets/cec-videos/agree_considered/juhm_agree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_considered/mamm_agree_considered_%03d.png ~/.keras/datasets/cec-videos/agree_considered/mamm_agree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_continue/islf_agree_continue_%03d.png ~/.keras/datasets/cec-videos/agree_continue/islf_agree_continue.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_continue/kabf_agree_continue_%03d.png ~/.keras/datasets/cec-videos/agree_continue/kabf_agree_continue.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_continue/lekf_agree_continue_%03d.png ~/.keras/datasets/cec-videos/agree_continue/lekf_agree_continue.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_continue/milf_agree_continue_%03d.png ~/.keras/datasets/cec-videos/agree_continue/milf_agree_continue.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_continue/silf_agree_continue_%03d.png ~/.keras/datasets/cec-videos/agree_continue/silf_agree_continue.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_continue/cawm_agree_continue_%03d.png ~/.keras/datasets/cec-videos/agree_continue/cawm_agree_continue.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_continue/chsm_agree_continue_%03d.png ~/.keras/datasets/cec-videos/agree_continue/chsm_agree_continue.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_continue/jakm_agree_continue_%03d.png ~/.keras/datasets/cec-videos/agree_continue/jakm_agree_continue.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_continue/juhm_agree_continue_%03d.png ~/.keras/datasets/cec-videos/agree_continue/juhm_agree_continue.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_continue/mamm_agree_continue_%03d.png ~/.keras/datasets/cec-videos/agree_continue/mamm_agree_continue.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_pure/islf_agree_%03d.png ~/.keras/datasets/cec-videos/agree_pure/islf_agree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_pure/kabf_agree_%03d.png ~/.keras/datasets/cec-videos/agree_pure/kabf_agree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_pure/lekf_agree_%03d.png ~/.keras/datasets/cec-videos/agree_pure/lekf_agree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_pure/milf_agree_%03d.png ~/.keras/datasets/cec-videos/agree_pure/milf_agree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_pure/silf_agree_%03d.png ~/.keras/datasets/cec-videos/agree_pure/silf_agree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_pure/cawm_agree_%03d.png ~/.keras/datasets/cec-videos/agree_pure/cawm_agree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_pure/chsm_agree_%03d.png ~/.keras/datasets/cec-videos/agree_pure/chsm_agree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_pure/jakm_agree_%03d.png ~/.keras/datasets/cec-videos/agree_pure/jakm_agree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_pure/juhm_agree_%03d.png ~/.keras/datasets/cec-videos/agree_pure/juhm_agree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_pure/mamm_agree_%03d.png ~/.keras/datasets/cec-videos/agree_pure/mamm_agree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_reluctant/islf_agree_reluctant_%03d.png ~/.keras/datasets/cec-videos/agree_reluctant/islf_agree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_reluctant/kabf_agree_reluctant_%03d.png ~/.keras/datasets/cec-videos/agree_reluctant/kabf_agree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_reluctant/lekf_agree_reluctant_%03d.png ~/.keras/datasets/cec-videos/agree_reluctant/lekf_agree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_reluctant/milf_agree_reluctant_%03d.png ~/.keras/datasets/cec-videos/agree_reluctant/milf_agree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_reluctant/silf_agree_reluctant_%03d.png ~/.keras/datasets/cec-videos/agree_reluctant/silf_agree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_reluctant/cawm_agree_reluctant_%03d.png ~/.keras/datasets/cec-videos/agree_reluctant/cawm_agree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_reluctant/chsm_agree_reluctant_%03d.png ~/.keras/datasets/cec-videos/agree_reluctant/chsm_agree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_reluctant/jakm_agree_reluctant_%03d.png ~/.keras/datasets/cec-videos/agree_reluctant/jakm_agree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_reluctant/juhm_agree_reluctant_%03d.png ~/.keras/datasets/cec-videos/agree_reluctant/juhm_agree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/agree_reluctant/mamm_agree_reluctant_%03d.png ~/.keras/datasets/cec-videos/agree_reluctant/mamm_agree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/aha-light_bulb_moment/islf_aha_%03d.png ~/.keras/datasets/cec-videos/aha-light_bulb_moment/islf_aha-light_bulb_moment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/aha-light_bulb_moment/kabf_aha_%03d.png ~/.keras/datasets/cec-videos/aha-light_bulb_moment/kabf_aha-light_bulb_moment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/aha-light_bulb_moment/lekf_aha_%03d.png ~/.keras/datasets/cec-videos/aha-light_bulb_moment/lekf_aha-light_bulb_moment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/aha-light_bulb_moment/milf_aha_%03d.png ~/.keras/datasets/cec-videos/aha-light_bulb_moment/milf_aha-light_bulb_moment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/aha-light_bulb_moment/silf_aha_%03d.png ~/.keras/datasets/cec-videos/aha-light_bulb_moment/silf_aha-light_bulb_moment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/aha-light_bulb_moment/cawm_aha_%03d.png ~/.keras/datasets/cec-videos/aha-light_bulb_moment/cawm_aha-light_bulb_moment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/aha-light_bulb_moment/chsm_aha_%03d.png ~/.keras/datasets/cec-videos/aha-light_bulb_moment/chsm_aha-light_bulb_moment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/aha-light_bulb_moment/jakm_aha_%03d.png ~/.keras/datasets/cec-videos/aha-light_bulb_moment/jakm_aha-light_bulb_moment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/aha-light_bulb_moment/juhm_aha_%03d.png ~/.keras/datasets/cec-videos/aha-light_bulb_moment/juhm_aha-light_bulb_moment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/aha-light_bulb_moment/mamm_aha_%03d.png ~/.keras/datasets/cec-videos/aha-light_bulb_moment/mamm_aha-light_bulb_moment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_bothered/islf_annoyed_bothered_%03d.png ~/.keras/datasets/cec-videos/annoyed_bothered/islf_annoyed_bothered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_bothered/kabf_annoyed_bothered_%03d.png ~/.keras/datasets/cec-videos/annoyed_bothered/kabf_annoyed_bothered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_bothered/lekf_annoyed_bothered_%03d.png ~/.keras/datasets/cec-videos/annoyed_bothered/lekf_annoyed_bothered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_bothered/milf_annoyed_bothered_%03d.png ~/.keras/datasets/cec-videos/annoyed_bothered/milf_annoyed_bothered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_bothered/silf_annoyed_bothered_%03d.png ~/.keras/datasets/cec-videos/annoyed_bothered/silf_annoyed_bothered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_bothered/cawm_annoyed_bothered_%03d.png ~/.keras/datasets/cec-videos/annoyed_bothered/cawm_annoyed_bothered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_bothered/chsm_annoyed_bothered_%03d.png ~/.keras/datasets/cec-videos/annoyed_bothered/chsm_annoyed_bothered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_bothered/jakm_annoyed_bothered_%03d.png ~/.keras/datasets/cec-videos/annoyed_bothered/jakm_annoyed_bothered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_bothered/juhm_annoyed_bothered_%03d.png ~/.keras/datasets/cec-videos/annoyed_bothered/juhm_annoyed_bothered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_bothered/mamm_annoyed_bothered_%03d.png ~/.keras/datasets/cec-videos/annoyed_bothered/mamm_annoyed_bothered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_rolling-eyes/islf_annoyed-eyeroll_%03d.png ~/.keras/datasets/cec-videos/annoyed_rolling-eyes/islf_annoyed_rolling-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_rolling-eyes/kabf_annoyed_eyeroll_%03d.png ~/.keras/datasets/cec-videos/annoyed_rolling-eyes/kabf_annoyed_rolling-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_rolling-eyes/lekf_annoyed_eyeroll_%03d.png ~/.keras/datasets/cec-videos/annoyed_rolling-eyes/lekf_annoyed_rolling-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_rolling-eyes/milf_annoyed-eyeroll_%03d.png ~/.keras/datasets/cec-videos/annoyed_rolling-eyes/milf_annoyed_rolling-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_rolling-eyes/silf_annoyed-eyeroll_%03d.png ~/.keras/datasets/cec-videos/annoyed_rolling-eyes/silf_annoyed_rolling-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_rolling-eyes/cawm_annoyed-eyeroll_%03d.png ~/.keras/datasets/cec-videos/annoyed_rolling-eyes/cawm_annoyed_rolling-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_rolling-eyes/chsm_annoyed-eyeroll_%03d.png ~/.keras/datasets/cec-videos/annoyed_rolling-eyes/chsm_annoyed_rolling-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_rolling-eyes/jakm_annoyed-eyeroll_%03d.png ~/.keras/datasets/cec-videos/annoyed_rolling-eyes/jakm_annoyed_rolling-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_rolling-eyes/juhm_annoyed_eyeroll_%03d.png ~/.keras/datasets/cec-videos/annoyed_rolling-eyes/juhm_annoyed_rolling-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/annoyed_rolling-eyes/mamm_annoyed-eyeroll_%03d.png ~/.keras/datasets/cec-videos/annoyed_rolling-eyes/mamm_annoyed_rolling-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/arrogant/islf_arrogant_%03d.png ~/.keras/datasets/cec-videos/arrogant/islf_arrogant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/arrogant/kabf_arrogant_%03d.png ~/.keras/datasets/cec-videos/arrogant/kabf_arrogant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/arrogant/lekf_arrogant_%03d.png ~/.keras/datasets/cec-videos/arrogant/lekf_arrogant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/arrogant/milf_arrogant_%03d.png ~/.keras/datasets/cec-videos/arrogant/milf_arrogant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/arrogant/silf_arrogant_%03d.png ~/.keras/datasets/cec-videos/arrogant/silf_arrogant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/arrogant/cawm_arrogant_%03d.png ~/.keras/datasets/cec-videos/arrogant/cawm_arrogant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/arrogant/chsm_arrogant_%03d.png ~/.keras/datasets/cec-videos/arrogant/chsm_arrogant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/arrogant/jakm_arrogant_%03d.png ~/.keras/datasets/cec-videos/arrogant/jakm_arrogant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/arrogant/juhm_arrogant_%03d.png ~/.keras/datasets/cec-videos/arrogant/juhm_arrogant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/arrogant/mamm_arrogant_%03d.png ~/.keras/datasets/cec-videos/arrogant/mamm_arrogant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/bored/islf_bored_%03d.png ~/.keras/datasets/cec-videos/bored/islf_bored.avi
ffmpeg -y -i ~/.keras/large-mpi-db/bored/kabf_bored_%03d.png ~/.keras/datasets/cec-videos/bored/kabf_bored.avi
ffmpeg -y -i ~/.keras/large-mpi-db/bored/lekf_bored_%03d.png ~/.keras/datasets/cec-videos/bored/lekf_bored.avi
ffmpeg -y -i ~/.keras/large-mpi-db/bored/milf_bored_%03d.png ~/.keras/datasets/cec-videos/bored/milf_bored.avi
ffmpeg -y -i ~/.keras/large-mpi-db/bored/silf_bored_%03d.png ~/.keras/datasets/cec-videos/bored/silf_bored.avi
ffmpeg -y -i ~/.keras/large-mpi-db/bored/cawm_bored_%03d.png ~/.keras/datasets/cec-videos/bored/cawm_bored.avi
ffmpeg -y -i ~/.keras/large-mpi-db/bored/chsm_bored_%03d.png ~/.keras/datasets/cec-videos/bored/chsm_bored.avi
ffmpeg -y -i ~/.keras/large-mpi-db/bored/jakm_bored_%03d.png ~/.keras/datasets/cec-videos/bored/jakm_bored.avi
ffmpeg -y -i ~/.keras/large-mpi-db/bored/juhm_bored_%03d.png ~/.keras/datasets/cec-videos/bored/juhm_bored.avi
ffmpeg -y -i ~/.keras/large-mpi-db/bored/mamm_bored_%03d.png ~/.keras/datasets/cec-videos/bored/mamm_bored.avi
ffmpeg -y -i ~/.keras/large-mpi-db/compassion/islf_compassion_%03d.png ~/.keras/datasets/cec-videos/compassion/islf_compassion.avi
ffmpeg -y -i ~/.keras/large-mpi-db/compassion/kabf_compassion_%03d.png ~/.keras/datasets/cec-videos/compassion/kabf_compassion.avi
ffmpeg -y -i ~/.keras/large-mpi-db/compassion/lekf_compassion_%03d.png ~/.keras/datasets/cec-videos/compassion/lekf_compassion.avi
ffmpeg -y -i ~/.keras/large-mpi-db/compassion/milf_compassion_%03d.png ~/.keras/datasets/cec-videos/compassion/milf_compassion.avi
ffmpeg -y -i ~/.keras/large-mpi-db/compassion/silf_compassion_%03d.png ~/.keras/datasets/cec-videos/compassion/silf_compassion.avi
ffmpeg -y -i ~/.keras/large-mpi-db/compassion/cawm_compassion_%03d.png ~/.keras/datasets/cec-videos/compassion/cawm_compassion.avi
ffmpeg -y -i ~/.keras/large-mpi-db/compassion/chsm_compassion_%03d.png ~/.keras/datasets/cec-videos/compassion/chsm_compassion.avi
ffmpeg -y -i ~/.keras/large-mpi-db/compassion/jakm_compassion_%03d.png ~/.keras/datasets/cec-videos/compassion/jakm_compassion.avi
ffmpeg -y -i ~/.keras/large-mpi-db/compassion/juhm_compassion_%03d.png ~/.keras/datasets/cec-videos/compassion/juhm_compassion.avi
ffmpeg -y -i ~/.keras/large-mpi-db/compassion/mamm_compassion_%03d.png ~/.keras/datasets/cec-videos/compassion/mamm_compassion.avi
ffmpeg -y -i ~/.keras/large-mpi-db/confused/islf_confused_%03d.png ~/.keras/datasets/cec-videos/confused/islf_confused.avi
ffmpeg -y -i ~/.keras/large-mpi-db/confused/kabf_confused_%03d.png ~/.keras/datasets/cec-videos/confused/kabf_confused.avi
ffmpeg -y -i ~/.keras/large-mpi-db/confused/lekf_confused_%03d.png ~/.keras/datasets/cec-videos/confused/lekf_confused.avi
ffmpeg -y -i ~/.keras/large-mpi-db/confused/milf_confused_%03d.png ~/.keras/datasets/cec-videos/confused/milf_confused.avi
ffmpeg -y -i ~/.keras/large-mpi-db/confused/silf_confused_%03d.png ~/.keras/datasets/cec-videos/confused/silf_confused.avi
ffmpeg -y -i ~/.keras/large-mpi-db/confused/cawm_confused_%03d.png ~/.keras/datasets/cec-videos/confused/cawm_confused.avi
ffmpeg -y -i ~/.keras/large-mpi-db/confused/chsm_confused_%03d.png ~/.keras/datasets/cec-videos/confused/chsm_confused.avi
ffmpeg -y -i ~/.keras/large-mpi-db/confused/jakm_confused_%03d.png ~/.keras/datasets/cec-videos/confused/jakm_confused.avi
ffmpeg -y -i ~/.keras/large-mpi-db/confused/juhm_confused_%03d.png ~/.keras/datasets/cec-videos/confused/juhm_confused.avi
ffmpeg -y -i ~/.keras/large-mpi-db/confused/mamm_confused_%03d.png ~/.keras/datasets/cec-videos/confused/mamm_confused.avi
ffmpeg -y -i ~/.keras/large-mpi-db/contempt/islf_contempt_%03d.png ~/.keras/datasets/cec-videos/contempt/islf_contempt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/contempt/kabf_contempt_%03d.png ~/.keras/datasets/cec-videos/contempt/kabf_contempt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/contempt/lekf_contempt_%03d.png ~/.keras/datasets/cec-videos/contempt/lekf_contempt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/contempt/milf_contempt_%03d.png ~/.keras/datasets/cec-videos/contempt/milf_contempt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/contempt/silf_contempt_%03d.png ~/.keras/datasets/cec-videos/contempt/silf_contempt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/contempt/cawm_contempt_%03d.png ~/.keras/datasets/cec-videos/contempt/cawm_contempt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/contempt/chsm_contempt_%03d.png ~/.keras/datasets/cec-videos/contempt/chsm_contempt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/contempt/jakm_contempt_%03d.png ~/.keras/datasets/cec-videos/contempt/jakm_contempt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/contempt/juhm_contempt_%03d.png ~/.keras/datasets/cec-videos/contempt/juhm_contempt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/contempt/mamm_contempt_%03d.png ~/.keras/datasets/cec-videos/contempt/mamm_contempt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_considered/islf_disagree_considered_%03d.png ~/.keras/datasets/cec-videos/disagree_considered/islf_disagree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_considered/kabf_disagree_considered_%03d.png ~/.keras/datasets/cec-videos/disagree_considered/kabf_disagree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_considered/lekf_disagree_considered_%03d.png ~/.keras/datasets/cec-videos/disagree_considered/lekf_disagree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_considered/milf_disagree_considered_%03d.png ~/.keras/datasets/cec-videos/disagree_considered/milf_disagree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_considered/silf_disagree_considered_%03d.png ~/.keras/datasets/cec-videos/disagree_considered/silf_disagree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_considered/cawm_disagree_considered_%03d.png ~/.keras/datasets/cec-videos/disagree_considered/cawm_disagree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_considered/chsm_disagree_considered_%03d.png ~/.keras/datasets/cec-videos/disagree_considered/chsm_disagree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_considered/jakm_disagree_considered_%03d.png ~/.keras/datasets/cec-videos/disagree_considered/jakm_disagree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_considered/juhm_disagree_considered_%03d.png ~/.keras/datasets/cec-videos/disagree_considered/juhm_disagree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_considered/mamm_disagree_considered_%03d.png ~/.keras/datasets/cec-videos/disagree_considered/mamm_disagree_considered.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_pure/islf_disagree_%03d.png ~/.keras/datasets/cec-videos/disagree_pure/islf_disagree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_pure/kabf_disagree_%03d.png ~/.keras/datasets/cec-videos/disagree_pure/kabf_disagree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_pure/lekf_disagree_%03d.png ~/.keras/datasets/cec-videos/disagree_pure/lekf_disagree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_pure/milf_disagree_%03d.png ~/.keras/datasets/cec-videos/disagree_pure/milf_disagree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_pure/silf_disagree_%03d.png ~/.keras/datasets/cec-videos/disagree_pure/silf_disagree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_pure/cawm_disagree_%03d.png ~/.keras/datasets/cec-videos/disagree_pure/cawm_disagree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_pure/chsm_disagree_%03d.png ~/.keras/datasets/cec-videos/disagree_pure/chsm_disagree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_pure/jakm_disagree_%03d.png ~/.keras/datasets/cec-videos/disagree_pure/jakm_disagree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_pure/juhm_disagree_%03d.png ~/.keras/datasets/cec-videos/disagree_pure/juhm_disagree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_pure/mamm_disagree_%03d.png ~/.keras/datasets/cec-videos/disagree_pure/mamm_disagree_pure.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_reluctant/islf_disagree_reluctant_%03d.png ~/.keras/datasets/cec-videos/disagree_reluctant/islf_disagree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_reluctant/kabf_disagree_reluctant_%03d.png ~/.keras/datasets/cec-videos/disagree_reluctant/kabf_disagree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_reluctant/lekf_disagree_reluctant_%03d.png ~/.keras/datasets/cec-videos/disagree_reluctant/lekf_disagree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_reluctant/milf_disagree_reluctant_%03d.png ~/.keras/datasets/cec-videos/disagree_reluctant/milf_disagree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_reluctant/silf_disagree_reluctant_%03d.png ~/.keras/datasets/cec-videos/disagree_reluctant/silf_disagree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_reluctant/cawm_disagree_reluctant_%03d.png ~/.keras/datasets/cec-videos/disagree_reluctant/cawm_disagree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_reluctant/chsm_disagree_reluctant_%03d.png ~/.keras/datasets/cec-videos/disagree_reluctant/chsm_disagree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_reluctant/jakm_disagree_reluctant_%03d.png ~/.keras/datasets/cec-videos/disagree_reluctant/jakm_disagree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_reluctant/juhm_disagree_reluctant_%03d.png ~/.keras/datasets/cec-videos/disagree_reluctant/juhm_disagree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disagree_reluctant/mamm_disagree_reluctant_%03d.png ~/.keras/datasets/cec-videos/disagree_reluctant/mamm_disagree_reluctant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disbelief/islf_disbelief_%03d.png ~/.keras/datasets/cec-videos/disbelief/islf_disbelief.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disbelief/kabf_disbelief_%03d.png ~/.keras/datasets/cec-videos/disbelief/kabf_disbelief.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disbelief/lekf_disbelief_%03d.png ~/.keras/datasets/cec-videos/disbelief/lekf_disbelief.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disbelief/milf_disbelief_%03d.png ~/.keras/datasets/cec-videos/disbelief/milf_disbelief.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disbelief/silf_disbelief_%03d.png ~/.keras/datasets/cec-videos/disbelief/silf_disbelief.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disbelief/cawm_disbelief_%03d.png ~/.keras/datasets/cec-videos/disbelief/cawm_disbelief.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disbelief/chsm_disbelief_%03d.png ~/.keras/datasets/cec-videos/disbelief/chsm_disbelief.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disbelief/jakm_disbelief_%03d.png ~/.keras/datasets/cec-videos/disbelief/jakm_disbelief.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disbelief/juhm_disbelief_%03d.png ~/.keras/datasets/cec-videos/disbelief/juhm_disbelief.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disbelief/mamm_disbelief_%03d.png ~/.keras/datasets/cec-videos/disbelief/mamm_disbelief.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disgust/islf_disgust_%03d.png ~/.keras/datasets/cec-videos/disgust/islf_disgust.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disgust/kabf_disgust_%03d.png ~/.keras/datasets/cec-videos/disgust/kabf_disgust.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disgust/lekf_disgust_%03d.png ~/.keras/datasets/cec-videos/disgust/lekf_disgust.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disgust/milf_disgust_%03d.png ~/.keras/datasets/cec-videos/disgust/milf_disgust.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disgust/silf_disgust_%03d.png ~/.keras/datasets/cec-videos/disgust/silf_disgust.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disgust/cawm_disgust_%03d.png ~/.keras/datasets/cec-videos/disgust/cawm_disgust.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disgust/chsm_disgust_%03d.png ~/.keras/datasets/cec-videos/disgust/chsm_disgust.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disgust/jakm_disgust_%03d.png ~/.keras/datasets/cec-videos/disgust/jakm_disgust.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disgust/juhm_disgust_%03d.png ~/.keras/datasets/cec-videos/disgust/juhm_disgust.avi
ffmpeg -y -i ~/.keras/large-mpi-db/disgust/mamm_disgust_%03d.png ~/.keras/datasets/cec-videos/disgust/mamm_disgust.avi
ffmpeg -y -i ~/.keras/large-mpi-db/embarrassment/islf_embarrassment_%03d.png ~/.keras/datasets/cec-videos/embarrassment/islf_embarrassment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/embarrassment/kabf_embarrassment_%03d.png ~/.keras/datasets/cec-videos/embarrassment/kabf_embarrassment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/embarrassment/lekf_embarrassment_%03d.png ~/.keras/datasets/cec-videos/embarrassment/lekf_embarrassment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/embarrassment/milf_embarrassment_%03d.png ~/.keras/datasets/cec-videos/embarrassment/milf_embarrassment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/embarrassment/silf_embarrassment_%03d.png ~/.keras/datasets/cec-videos/embarrassment/silf_embarrassment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/embarrassment/cawm_embarrassment_%03d.png ~/.keras/datasets/cec-videos/embarrassment/cawm_embarrassment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/embarrassment/chsm_embarrassment_%03d.png ~/.keras/datasets/cec-videos/embarrassment/chsm_embarrassment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/embarrassment/jakm_embarrassment_%03d.png ~/.keras/datasets/cec-videos/embarrassment/jakm_embarrassment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/embarrassment/juhm_embarrassment_%03d.png ~/.keras/datasets/cec-videos/embarrassment/juhm_embarrassment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/embarrassment/mamm_embarrassment_%03d.png ~/.keras/datasets/cec-videos/embarrassment/mamm_embarrassment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_oops/islf_fear_oops_%03d.png ~/.keras/datasets/cec-videos/fear_oops/islf_fear_oops.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_oops/kabf_fear_oops_%03d.png ~/.keras/datasets/cec-videos/fear_oops/kabf_fear_oops.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_oops/lekf_fear_oops_%03d.png ~/.keras/datasets/cec-videos/fear_oops/lekf_fear_oops.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_oops/milf_fear_oops_%03d.png ~/.keras/datasets/cec-videos/fear_oops/milf_fear_oops.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_oops/silf_fear_oops_%03d.png ~/.keras/datasets/cec-videos/fear_oops/silf_fear_oops.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_oops/cawm_fear_oops_%03d.png ~/.keras/datasets/cec-videos/fear_oops/cawm_fear_oops.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_oops/chsm_fear_oops_%03d.png ~/.keras/datasets/cec-videos/fear_oops/chsm_fear_oops.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_oops/jakm_fear_oops_%03d.png ~/.keras/datasets/cec-videos/fear_oops/jakm_fear_oops.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_oops/juhm_fear_oops_%03d.png ~/.keras/datasets/cec-videos/fear_oops/juhm_fear_oops.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_oops/mamm_fear_oops_%03d.png ~/.keras/datasets/cec-videos/fear_oops/mamm_fear_oops.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_terror/islf_fear_terror_%03d.png ~/.keras/datasets/cec-videos/fear_terror/islf_fear_terror.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_terror/kabf_fear_terror_%03d.png ~/.keras/datasets/cec-videos/fear_terror/kabf_fear_terror.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_terror/lekf_fear_terror_%03d.png ~/.keras/datasets/cec-videos/fear_terror/lekf_fear_terror.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_terror/milf_fear_terror_%03d.png ~/.keras/datasets/cec-videos/fear_terror/milf_fear_terror.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_terror/silf_fear_terror_%03d.png ~/.keras/datasets/cec-videos/fear_terror/silf_fear_terror.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_terror/cawm_fear_terror_%03d.png ~/.keras/datasets/cec-videos/fear_terror/cawm_fear_terror.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_terror/chsm_fear_terror_%03d.png ~/.keras/datasets/cec-videos/fear_terror/chsm_fear_terror.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_terror/jakm_fear_terror_%03d.png ~/.keras/datasets/cec-videos/fear_terror/jakm_fear_terror.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_terror/juhm_fear_terror_%03d.png ~/.keras/datasets/cec-videos/fear_terror/juhm_fear_terror.avi
ffmpeg -y -i ~/.keras/large-mpi-db/fear_terror/mamm_fear_terror_%03d.png ~/.keras/datasets/cec-videos/fear_terror/mamm_fear_terror.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_achievement/islf_happy_achievement_%03d.png ~/.keras/datasets/cec-videos/happy_achievement/islf_happy_achievement.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_achievement/kabf_happy_achievement_%03d.png ~/.keras/datasets/cec-videos/happy_achievement/kabf_happy_achievement.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_achievement/lekf_happy_achievement_%03d.png ~/.keras/datasets/cec-videos/happy_achievement/lekf_happy_achievement.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_achievement/milf_happy_achievement_%03d.png ~/.keras/datasets/cec-videos/happy_achievement/milf_happy_achievement.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_achievement/silf_happy_achievement_%03d.png ~/.keras/datasets/cec-videos/happy_achievement/silf_happy_achievement.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_achievement/cawm_happy_achievement_%03d.png ~/.keras/datasets/cec-videos/happy_achievement/cawm_happy_achievement.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_achievement/chsm_happy_achievement_%03d.png ~/.keras/datasets/cec-videos/happy_achievement/chsm_happy_achievement.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_achievement/jakm_happy_achievement_%03d.png ~/.keras/datasets/cec-videos/happy_achievement/jakm_happy_achievement.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_achievement/juhm_happy_achievement_%03d.png ~/.keras/datasets/cec-videos/happy_achievement/juhm_happy_achievement.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_achievement/mamm_happy_achievement_%03d.png ~/.keras/datasets/cec-videos/happy_achievement/mamm_happy_achievement.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_laughing/islf_happy_laughing_%03d.png ~/.keras/datasets/cec-videos/happy_laughing/islf_happy_laughing.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_laughing/kabf_happy_laughing_%03d.png ~/.keras/datasets/cec-videos/happy_laughing/kabf_happy_laughing.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_laughing/lekf_happy_laughing_%03d.png ~/.keras/datasets/cec-videos/happy_laughing/lekf_happy_laughing.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_laughing/milf_happy_laughing_%03d.png ~/.keras/datasets/cec-videos/happy_laughing/milf_happy_laughing.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_laughing/silf_happy_laughing_%03d.png ~/.keras/datasets/cec-videos/happy_laughing/silf_happy_laughing.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_laughing/cawm_happy_laughing_%03d.png ~/.keras/datasets/cec-videos/happy_laughing/cawm_happy_laughing.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_laughing/chsm_happy_laughing_%03d.png ~/.keras/datasets/cec-videos/happy_laughing/chsm_happy_laughing.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_laughing/jakm_happy_laughing_%03d.png ~/.keras/datasets/cec-videos/happy_laughing/jakm_happy_laughing.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_laughing/juhm_happy_laughing_%03d.png ~/.keras/datasets/cec-videos/happy_laughing/juhm_happy_laughing.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_laughing/mamm_happy_laughing_%03d.png ~/.keras/datasets/cec-videos/happy_laughing/mamm_happy_laughing.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_satiated/islf_happy_satiated_%03d.png ~/.keras/datasets/cec-videos/happy_satiated/islf_happy_satiated.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_satiated/kabf_happy_satiated_%03d.png ~/.keras/datasets/cec-videos/happy_satiated/kabf_happy_satiated.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_satiated/lekf_happy_satiated_%03d.png ~/.keras/datasets/cec-videos/happy_satiated/lekf_happy_satiated.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_satiated/milf_happy_satiated_%03d.png ~/.keras/datasets/cec-videos/happy_satiated/milf_happy_satiated.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_satiated/silf_happy_satiated_%03d.png ~/.keras/datasets/cec-videos/happy_satiated/silf_happy_satiated.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_satiated/cawm_happy_satiated_%03d.png ~/.keras/datasets/cec-videos/happy_satiated/cawm_happy_satiated.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_satiated/chsm_happy_satiated_%03d.png ~/.keras/datasets/cec-videos/happy_satiated/chsm_happy_satiated.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_satiated/jakm_happy_satiated_%03d.png ~/.keras/datasets/cec-videos/happy_satiated/jakm_happy_satiated.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_satiated/juhm_happy_satiated_%03d.png ~/.keras/datasets/cec-videos/happy_satiated/juhm_happy_satiated.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_satiated/mamm_happy_satiated_%03d.png ~/.keras/datasets/cec-videos/happy_satiated/mamm_happy_satiated.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_schadenfreude/islf_schadenfreude_%03d.png ~/.keras/datasets/cec-videos/happy_schadenfreude/islf_happy_schadenfreude.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_schadenfreude/kabf_schadenfreude_%03d.png ~/.keras/datasets/cec-videos/happy_schadenfreude/kabf_happy_schadenfreude.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_schadenfreude/lekf_schadenfreude_%03d.png ~/.keras/datasets/cec-videos/happy_schadenfreude/lekf_happy_schadenfreude.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_schadenfreude/milf_schadenfreude_%03d.png ~/.keras/datasets/cec-videos/happy_schadenfreude/milf_happy_schadenfreude.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_schadenfreude/silf_schadenfreude_%03d.png ~/.keras/datasets/cec-videos/happy_schadenfreude/silf_happy_schadenfreude.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_schadenfreude/cawm_schadenfreude_%03d.png ~/.keras/datasets/cec-videos/happy_schadenfreude/cawm_happy_schadenfreude.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_schadenfreude/chsm_schadenfreude_%03d.png ~/.keras/datasets/cec-videos/happy_schadenfreude/chsm_happy_schadenfreude.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_schadenfreude/jakm_schadenfreude_%03d.png ~/.keras/datasets/cec-videos/happy_schadenfreude/jakm_happy_schadenfreude.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_schadenfreude/juhm_schadenfreude_%03d.png ~/.keras/datasets/cec-videos/happy_schadenfreude/juhm_happy_schadenfreude.avi
ffmpeg -y -i ~/.keras/large-mpi-db/happy_schadenfreude/mamm_schadenfreude_%03d.png ~/.keras/datasets/cec-videos/happy_schadenfreude/mamm_happy_schadenfreude.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_did_not_hear/islf_dont_hear_%03d.png ~/.keras/datasets/cec-videos/I_did_not_hear/islf_I_did_not_hear.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_did_not_hear/kabf_dont_hear_%03d.png ~/.keras/datasets/cec-videos/I_did_not_hear/kabf_I_did_not_hear.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_did_not_hear/lekf_dont_hear_%03d.png ~/.keras/datasets/cec-videos/I_did_not_hear/lekf_I_did_not_hear.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_did_not_hear/milf_dont_hear_%03d.png ~/.keras/datasets/cec-videos/I_did_not_hear/milf_I_did_not_hear.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_did_not_hear/silf_dont_hear_%03d.png ~/.keras/datasets/cec-videos/I_did_not_hear/silf_I_did_not_hear.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_did_not_hear/cawm_dont_hear_%03d.png ~/.keras/datasets/cec-videos/I_did_not_hear/cawm_I_did_not_hear.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_did_not_hear/chsm_dont_hear_%03d.png ~/.keras/datasets/cec-videos/I_did_not_hear/chsm_I_did_not_hear.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_did_not_hear/jakm_dont_hear_%03d.png ~/.keras/datasets/cec-videos/I_did_not_hear/jakm_I_did_not_hear.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_did_not_hear/juhm_dont_hear_%03d.png ~/.keras/datasets/cec-videos/I_did_not_hear/juhm_I_did_not_hear.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_did_not_hear/mamm_dont_hear_%03d.png ~/.keras/datasets/cec-videos/I_did_not_hear/mamm_I_did_not_hear.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_care/islf_dont_care_%03d.png ~/.keras/datasets/cec-videos/I_dont_care/islf_I_dont_care.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_care/kabf_dont_care_%03d.png ~/.keras/datasets/cec-videos/I_dont_care/kabf_I_dont_care.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_care/lekf_dont_care_%03d.png ~/.keras/datasets/cec-videos/I_dont_care/lekf_I_dont_care.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_care/milf_dont_care_%03d.png ~/.keras/datasets/cec-videos/I_dont_care/milf_I_dont_care.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_care/silf_dont_care_%03d.png ~/.keras/datasets/cec-videos/I_dont_care/silf_I_dont_care.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_care/cawm_dont_care_%03d.png ~/.keras/datasets/cec-videos/I_dont_care/cawm_I_dont_care.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_care/chsm_dont_care_%03d.png ~/.keras/datasets/cec-videos/I_dont_care/chsm_I_dont_care.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_care/jakm_dont_care_%03d.png ~/.keras/datasets/cec-videos/I_dont_care/jakm_I_dont_care.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_care/juhm_dont_care_%03d.png ~/.keras/datasets/cec-videos/I_dont_care/juhm_I_dont_care.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_care/mamm_dont_care_%03d.png ~/.keras/datasets/cec-videos/I_dont_care/mamm_I_dont_care.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_know/islf_dont_know_%03d.png ~/.keras/datasets/cec-videos/I_dont_know/islf_I_dont_know.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_know/kabf_dont_know_%03d.png ~/.keras/datasets/cec-videos/I_dont_know/kabf_I_dont_know.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_know/lekf_dont_know_%03d.png ~/.keras/datasets/cec-videos/I_dont_know/lekf_I_dont_know.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_know/milf_dont_know_%03d.png ~/.keras/datasets/cec-videos/I_dont_know/milf_I_dont_know.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_know/silf_dont_know_%03d.png ~/.keras/datasets/cec-videos/I_dont_know/silf_I_dont_know.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_know/cawm_dont_know_%03d.png ~/.keras/datasets/cec-videos/I_dont_know/cawm_I_dont_know.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_know/chsm_dont_know_%03d.png ~/.keras/datasets/cec-videos/I_dont_know/chsm_I_dont_know.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_know/jakm_dont_know_%03d.png ~/.keras/datasets/cec-videos/I_dont_know/jakm_I_dont_know.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_know/juhm_dont_know_%03d.png ~/.keras/datasets/cec-videos/I_dont_know/juhm_I_dont_know.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_know/mamm_dont_know_%03d.png ~/.keras/datasets/cec-videos/I_dont_know/mamm_I_dont_know.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_understand/islf_dont_understand_%03d.png ~/.keras/datasets/cec-videos/I_dont_understand/islf_I_dont_understand.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_understand/kabf_dont_understand_%03d.png ~/.keras/datasets/cec-videos/I_dont_understand/kabf_I_dont_understand.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_understand/lekf_dont_understand_%03d.png ~/.keras/datasets/cec-videos/I_dont_understand/lekf_I_dont_understand.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_understand/milf_dont_understand_%03d.png ~/.keras/datasets/cec-videos/I_dont_understand/milf_I_dont_understand.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_understand/silf_dont_understand_%03d.png ~/.keras/datasets/cec-videos/I_dont_understand/silf_I_dont_understand.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_understand/cawm_dont_understand_%03d.png ~/.keras/datasets/cec-videos/I_dont_understand/cawm_I_dont_understand.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_understand/chsm_dont_understand_%03d.png ~/.keras/datasets/cec-videos/I_dont_understand/chsm_I_dont_understand.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_understand/jakm_dont_understand_%03d.png ~/.keras/datasets/cec-videos/I_dont_understand/jakm_I_dont_understand.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_understand/juhm_dont_understand_%03d.png ~/.keras/datasets/cec-videos/I_dont_understand/juhm_I_dont_understand.avi
ffmpeg -y -i ~/.keras/large-mpi-db/I_dont_understand/mamm_dont_understand_%03d.png ~/.keras/datasets/cec-videos/I_dont_understand/mamm_I_dont_understand.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_negative/islf_imagine-negative_%03d.png ~/.keras/datasets/cec-videos/imagine_negative/islf_imagine_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_negative/kabf_imagine-negative_%03d.png ~/.keras/datasets/cec-videos/imagine_negative/kabf_imagine_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_negative/lekf_imagine-negative_%03d.png ~/.keras/datasets/cec-videos/imagine_negative/lekf_imagine_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_negative/milf_imagine-negative_%03d.png ~/.keras/datasets/cec-videos/imagine_negative/milf_imagine_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_negative/silf_imagine-negative_%03d.png ~/.keras/datasets/cec-videos/imagine_negative/silf_imagine_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_negative/cawm_imagine-negative_%03d.png ~/.keras/datasets/cec-videos/imagine_negative/cawm_imagine_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_negative/chsm_imagine-negative_%03d.png ~/.keras/datasets/cec-videos/imagine_negative/chsm_imagine_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_negative/jakm_imagine-negative_%03d.png ~/.keras/datasets/cec-videos/imagine_negative/jakm_imagine_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_negative/juhm_imagine-negative_%03d.png ~/.keras/datasets/cec-videos/imagine_negative/juhm_imagine_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_negative/mamm_imagine-negative_%03d.png ~/.keras/datasets/cec-videos/imagine_negative/mamm_imagine_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_positive/islf_imagine-positive_%03d.png ~/.keras/datasets/cec-videos/imagine_positive/islf_imagine_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_positive/kabf_imagine-positive_%03d.png ~/.keras/datasets/cec-videos/imagine_positive/kabf_imagine_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_positive/lekf_imagine-positive_%03d.png ~/.keras/datasets/cec-videos/imagine_positive/lekf_imagine_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_positive/milf_imagine-positive_%03d.png ~/.keras/datasets/cec-videos/imagine_positive/milf_imagine_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_positive/silf_imagine-positive_%03d.png ~/.keras/datasets/cec-videos/imagine_positive/silf_imagine_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_positive/cawm_imagine-positive_%03d.png ~/.keras/datasets/cec-videos/imagine_positive/cawm_imagine_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_positive/chsm_imagine-positive_%03d.png ~/.keras/datasets/cec-videos/imagine_positive/chsm_imagine_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_positive/jakm_imagine-positive_%03d.png ~/.keras/datasets/cec-videos/imagine_positive/jakm_imagine_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_positive/juhm_imagine-positive_%03d.png ~/.keras/datasets/cec-videos/imagine_positive/juhm_imagine_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/imagine_positive/mamm_imagine-positive_%03d.png ~/.keras/datasets/cec-videos/imagine_positive/mamm_imagine_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/impressed/islf_impressed_%03d.png ~/.keras/datasets/cec-videos/impressed/islf_impressed.avi
ffmpeg -y -i ~/.keras/large-mpi-db/impressed/kabf_impressed_%03d.png ~/.keras/datasets/cec-videos/impressed/kabf_impressed.avi
ffmpeg -y -i ~/.keras/large-mpi-db/impressed/lekf_impressed_%03d.png ~/.keras/datasets/cec-videos/impressed/lekf_impressed.avi
ffmpeg -y -i ~/.keras/large-mpi-db/impressed/milf_impressed_%03d.png ~/.keras/datasets/cec-videos/impressed/milf_impressed.avi
ffmpeg -y -i ~/.keras/large-mpi-db/impressed/silf_impressed_%03d.png ~/.keras/datasets/cec-videos/impressed/silf_impressed.avi
ffmpeg -y -i ~/.keras/large-mpi-db/impressed/cawm_impressed_%03d.png ~/.keras/datasets/cec-videos/impressed/cawm_impressed.avi
ffmpeg -y -i ~/.keras/large-mpi-db/impressed/chsm_impressed_%03d.png ~/.keras/datasets/cec-videos/impressed/chsm_impressed.avi
ffmpeg -y -i ~/.keras/large-mpi-db/impressed/jakm_impressed_%03d.png ~/.keras/datasets/cec-videos/impressed/jakm_impressed.avi
ffmpeg -y -i ~/.keras/large-mpi-db/impressed/juhm_impressed_%03d.png ~/.keras/datasets/cec-videos/impressed/juhm_impressed.avi
ffmpeg -y -i ~/.keras/large-mpi-db/impressed/mamm_impressed_%03d.png ~/.keras/datasets/cec-videos/impressed/mamm_impressed.avi
ffmpeg -y -i ~/.keras/large-mpi-db/insecurity/islf_insecurity_%03d.png ~/.keras/datasets/cec-videos/insecurity/islf_insecurity.avi
ffmpeg -y -i ~/.keras/large-mpi-db/insecurity/kabf_insecurity_%03d.png ~/.keras/datasets/cec-videos/insecurity/kabf_insecurity.avi
ffmpeg -y -i ~/.keras/large-mpi-db/insecurity/lekf_insecurity_%03d.png ~/.keras/datasets/cec-videos/insecurity/lekf_insecurity.avi
ffmpeg -y -i ~/.keras/large-mpi-db/insecurity/milf_insecurity_%03d.png ~/.keras/datasets/cec-videos/insecurity/milf_insecurity.avi
ffmpeg -y -i ~/.keras/large-mpi-db/insecurity/silf_insecurity_%03d.png ~/.keras/datasets/cec-videos/insecurity/silf_insecurity.avi
ffmpeg -y -i ~/.keras/large-mpi-db/insecurity/cawm_insecurity_%03d.png ~/.keras/datasets/cec-videos/insecurity/cawm_insecurity.avi
ffmpeg -y -i ~/.keras/large-mpi-db/insecurity/chsm_insecurity_%03d.png ~/.keras/datasets/cec-videos/insecurity/chsm_insecurity.avi
ffmpeg -y -i ~/.keras/large-mpi-db/insecurity/jakm_insecurity_%03d.png ~/.keras/datasets/cec-videos/insecurity/jakm_insecurity.avi
ffmpeg -y -i ~/.keras/large-mpi-db/insecurity/juhm_insecurity_%03d.png ~/.keras/datasets/cec-videos/insecurity/juhm_insecurity.avi
ffmpeg -y -i ~/.keras/large-mpi-db/insecurity/mamm_insecurity_%03d.png ~/.keras/datasets/cec-videos/insecurity/mamm_insecurity.avi
ffmpeg -y -i ~/.keras/large-mpi-db/not_convinced/islf_not_convinced_%03d.png ~/.keras/datasets/cec-videos/not_convinced/islf_not_convinced.avi
ffmpeg -y -i ~/.keras/large-mpi-db/not_convinced/kabf_not_convinced_%03d.png ~/.keras/datasets/cec-videos/not_convinced/kabf_not_convinced.avi
ffmpeg -y -i ~/.keras/large-mpi-db/not_convinced/lekf_not_convinced_%03d.png ~/.keras/datasets/cec-videos/not_convinced/lekf_not_convinced.avi
ffmpeg -y -i ~/.keras/large-mpi-db/not_convinced/milf_not_convinced_%03d.png ~/.keras/datasets/cec-videos/not_convinced/milf_not_convinced.avi
ffmpeg -y -i ~/.keras/large-mpi-db/not_convinced/silf_not_convinced_%03d.png ~/.keras/datasets/cec-videos/not_convinced/silf_not_convinced.avi
ffmpeg -y -i ~/.keras/large-mpi-db/not_convinced/cawm_not_convinced_%03d.png ~/.keras/datasets/cec-videos/not_convinced/cawm_not_convinced.avi
ffmpeg -y -i ~/.keras/large-mpi-db/not_convinced/chsm_not_convinced_%03d.png ~/.keras/datasets/cec-videos/not_convinced/chsm_not_convinced.avi
ffmpeg -y -i ~/.keras/large-mpi-db/not_convinced/jakm_not_convinced_%03d.png ~/.keras/datasets/cec-videos/not_convinced/jakm_not_convinced.avi
ffmpeg -y -i ~/.keras/large-mpi-db/not_convinced/juhm_not_convinced_%03d.png ~/.keras/datasets/cec-videos/not_convinced/juhm_not_convinced.avi
ffmpeg -y -i ~/.keras/large-mpi-db/not_convinced/mamm_not_convinced_%03d.png ~/.keras/datasets/cec-videos/not_convinced/mamm_not_convinced.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_felt/islf_pain_felt_%03d.png ~/.keras/datasets/cec-videos/pain_felt/islf_pain_felt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_felt/kabf_pain_felt_%03d.png ~/.keras/datasets/cec-videos/pain_felt/kabf_pain_felt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_felt/lekf_pain_felt_%03d.png ~/.keras/datasets/cec-videos/pain_felt/lekf_pain_felt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_felt/milf_pain_felt_%03d.png ~/.keras/datasets/cec-videos/pain_felt/milf_pain_felt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_felt/silf_pain_felt_%03d.png ~/.keras/datasets/cec-videos/pain_felt/silf_pain_felt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_felt/cawm_pain_felt_%03d.png ~/.keras/datasets/cec-videos/pain_felt/cawm_pain_felt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_felt/chsm_pain_felt_%03d.png ~/.keras/datasets/cec-videos/pain_felt/chsm_pain_felt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_felt/jakm_pain_felt_%03d.png ~/.keras/datasets/cec-videos/pain_felt/jakm_pain_felt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_felt/juhm_pain_felt_%03d.png ~/.keras/datasets/cec-videos/pain_felt/juhm_pain_felt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_felt/mamm_pain_felt_%03d.png ~/.keras/datasets/cec-videos/pain_felt/mamm_pain_felt.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_seen/islf_pain_seen_%03d.png ~/.keras/datasets/cec-videos/pain_seen/islf_pain_seen.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_seen/kabf_pain_seen_%03d.png ~/.keras/datasets/cec-videos/pain_seen/kabf_pain_seen.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_seen/lekf_pain_seen_%03d.png ~/.keras/datasets/cec-videos/pain_seen/lekf_pain_seen.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_seen/milf_pain_seen_%03d.png ~/.keras/datasets/cec-videos/pain_seen/milf_pain_seen.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_seen/silf_pain_seen_%03d.png ~/.keras/datasets/cec-videos/pain_seen/silf_pain_seen.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_seen/cawm_pain_seen_%03d.png ~/.keras/datasets/cec-videos/pain_seen/cawm_pain_seen.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_seen/chsm_pain_seen_%03d.png ~/.keras/datasets/cec-videos/pain_seen/chsm_pain_seen.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_seen/jakm_pain_seen_%03d.png ~/.keras/datasets/cec-videos/pain_seen/jakm_pain_seen.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_seen/juhm_pain_seen_%03d.png ~/.keras/datasets/cec-videos/pain_seen/juhm_pain_seen.avi
ffmpeg -y -i ~/.keras/large-mpi-db/pain_seen/mamm_pain_seen_%03d.png ~/.keras/datasets/cec-videos/pain_seen/mamm_pain_seen.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_negative/islf_remember_negative_%03d.png ~/.keras/datasets/cec-videos/remember_negative/islf_remember_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_negative/kabf_remember_negative_%03d.png ~/.keras/datasets/cec-videos/remember_negative/kabf_remember_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_negative/lekf_remember_negative_%03d.png ~/.keras/datasets/cec-videos/remember_negative/lekf_remember_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_negative/milf_remember_negative_%03d.png ~/.keras/datasets/cec-videos/remember_negative/milf_remember_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_negative/silf_remember_negative_%03d.png ~/.keras/datasets/cec-videos/remember_negative/silf_remember_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_negative/cawm_remember_negative_%03d.png ~/.keras/datasets/cec-videos/remember_negative/cawm_remember_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_negative/chsm_remember_negative_%03d.png ~/.keras/datasets/cec-videos/remember_negative/chsm_remember_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_negative/jakm_remember_negative_%03d.png ~/.keras/datasets/cec-videos/remember_negative/jakm_remember_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_negative/juhm_remember_negative_%03d.png ~/.keras/datasets/cec-videos/remember_negative/juhm_remember_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_negative/mamm_remember_negative_%03d.png ~/.keras/datasets/cec-videos/remember_negative/mamm_remember_negative.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_positive/islf_remember_positive_%03d.png ~/.keras/datasets/cec-videos/remember_positive/islf_remember_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_positive/kabf_remember_positive_%03d.png ~/.keras/datasets/cec-videos/remember_positive/kabf_remember_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_positive/lekf_remember_positive_%03d.png ~/.keras/datasets/cec-videos/remember_positive/lekf_remember_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_positive/milf_remember_positive_%03d.png ~/.keras/datasets/cec-videos/remember_positive/milf_remember_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_positive/silf_remember_positive_%03d.png ~/.keras/datasets/cec-videos/remember_positive/silf_remember_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_positive/cawm_remember_positive_%03d.png ~/.keras/datasets/cec-videos/remember_positive/cawm_remember_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_positive/chsm_remember_positive_%03d.png ~/.keras/datasets/cec-videos/remember_positive/chsm_remember_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_positive/jakm_remember_positive_%03d.png ~/.keras/datasets/cec-videos/remember_positive/jakm_remember_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_positive/juhm_remember_positive_%03d.png ~/.keras/datasets/cec-videos/remember_positive/juhm_remember_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/remember_positive/mamm_remember_positive_%03d.png ~/.keras/datasets/cec-videos/remember_positive/mamm_remember_positive.avi
ffmpeg -y -i ~/.keras/large-mpi-db/sad/islf_sad_%03d.png ~/.keras/datasets/cec-videos/sad/islf_sad.avi
ffmpeg -y -i ~/.keras/large-mpi-db/sad/kabf_sad_%03d.png ~/.keras/datasets/cec-videos/sad/kabf_sad.avi
ffmpeg -y -i ~/.keras/large-mpi-db/sad/lekf_sad_%03d.png ~/.keras/datasets/cec-videos/sad/lekf_sad.avi
ffmpeg -y -i ~/.keras/large-mpi-db/sad/milf_sad_%03d.png ~/.keras/datasets/cec-videos/sad/milf_sad.avi
ffmpeg -y -i ~/.keras/large-mpi-db/sad/silf_sad_%03d.png ~/.keras/datasets/cec-videos/sad/silf_sad.avi
ffmpeg -y -i ~/.keras/large-mpi-db/sad/cawm_sad_%03d.png ~/.keras/datasets/cec-videos/sad/cawm_sad.avi
ffmpeg -y -i ~/.keras/large-mpi-db/sad/chsm_sad_%03d.png ~/.keras/datasets/cec-videos/sad/chsm_sad.avi
ffmpeg -y -i ~/.keras/large-mpi-db/sad/jakm_sad_%03d.png ~/.keras/datasets/cec-videos/sad/jakm_sad.avi
ffmpeg -y -i ~/.keras/large-mpi-db/sad/juhm_sad_%03d.png ~/.keras/datasets/cec-videos/sad/juhm_sad.avi
ffmpeg -y -i ~/.keras/large-mpi-db/sad/mamm_sad_%03d.png ~/.keras/datasets/cec-videos/sad/mamm_sad.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_encouraging/islf_smiling_encouraging_%03d.png ~/.keras/datasets/cec-videos/smiling_encouraging/islf_smiling_encouraging.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_encouraging/kabf_smiling_encouraging_%03d.png ~/.keras/datasets/cec-videos/smiling_encouraging/kabf_smiling_encouraging.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_encouraging/lekf_smiling_encouraging_%03d.png ~/.keras/datasets/cec-videos/smiling_encouraging/lekf_smiling_encouraging.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_encouraging/milf_smiling_encouraging_%03d.png ~/.keras/datasets/cec-videos/smiling_encouraging/milf_smiling_encouraging.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_encouraging/silf_smiling_encouraging_%03d.png ~/.keras/datasets/cec-videos/smiling_encouraging/silf_smiling_encouraging.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_encouraging/cawm_smiling_encouraging_%03d.png ~/.keras/datasets/cec-videos/smiling_encouraging/cawm_smiling_encouraging.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_encouraging/chsm_smiling_encouraging_%03d.png ~/.keras/datasets/cec-videos/smiling_encouraging/chsm_smiling_encouraging.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_encouraging/jakm_smiling_encouraging_%03d.png ~/.keras/datasets/cec-videos/smiling_encouraging/jakm_smiling_encouraging.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_encouraging/juhm_smiling_encouraging_%03d.png ~/.keras/datasets/cec-videos/smiling_encouraging/juhm_smiling_encouraging.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_encouraging/mamm_smiling_encouraging_%03d.png ~/.keras/datasets/cec-videos/smiling_encouraging/mamm_smiling_encouraging.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_endearment/islf_smiling_endearment_%03d.png ~/.keras/datasets/cec-videos/smiling_endearment/islf_smiling_endearment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_endearment/kabf_smiling_endearment_%03d.png ~/.keras/datasets/cec-videos/smiling_endearment/kabf_smiling_endearment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_endearment/lekf_smiling_endearment_%03d.png ~/.keras/datasets/cec-videos/smiling_endearment/lekf_smiling_endearment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_endearment/milf_smiling_endearment_%03d.png ~/.keras/datasets/cec-videos/smiling_endearment/milf_smiling_endearment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_endearment/silf_smiling_endearment_%03d.png ~/.keras/datasets/cec-videos/smiling_endearment/silf_smiling_endearment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_endearment/cawm_smiling_endearment_%03d.png ~/.keras/datasets/cec-videos/smiling_endearment/cawm_smiling_endearment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_endearment/chsm_smiling_endearment_%03d.png ~/.keras/datasets/cec-videos/smiling_endearment/chsm_smiling_endearment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_endearment/jakm_smiling_endearment_%03d.png ~/.keras/datasets/cec-videos/smiling_endearment/jakm_smiling_endearment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_endearment/juhm_smiling_endearment_%03d.png ~/.keras/datasets/cec-videos/smiling_endearment/juhm_smiling_endearment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_endearment/mamm_smiling_endearment_%03d.png ~/.keras/datasets/cec-videos/smiling_endearment/mamm_smiling_endearment.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_flirting/islf_smiling_flirting_%03d.png ~/.keras/datasets/cec-videos/smiling_flirting/islf_smiling_flirting.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_flirting/kabf_smiling_flirting_%03d.png ~/.keras/datasets/cec-videos/smiling_flirting/kabf_smiling_flirting.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_flirting/lekf_smiling_flirting_%03d.png ~/.keras/datasets/cec-videos/smiling_flirting/lekf_smiling_flirting.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_flirting/milf_smiling_flirting_%03d.png ~/.keras/datasets/cec-videos/smiling_flirting/milf_smiling_flirting.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_flirting/silf_smiling_flirting_%03d.png ~/.keras/datasets/cec-videos/smiling_flirting/silf_smiling_flirting.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_flirting/cawm_smiling_flirting_%03d.png ~/.keras/datasets/cec-videos/smiling_flirting/cawm_smiling_flirting.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_flirting/chsm_smiling_flirting_%03d.png ~/.keras/datasets/cec-videos/smiling_flirting/chsm_smiling_flirting.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_flirting/jakm_smiling_flirting_%03d.png ~/.keras/datasets/cec-videos/smiling_flirting/jakm_smiling_flirting.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_flirting/juhm_smiling_flirting_%03d.png ~/.keras/datasets/cec-videos/smiling_flirting/juhm_smiling_flirting.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_flirting/mamm_smiling_flirting_%03d.png ~/.keras/datasets/cec-videos/smiling_flirting/mamm_smiling_flirting.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sad-nostalgia/islf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/cec-videos/smiling_sad-nostalgia/islf_smiling_sad-nostalgia.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sad-nostalgia/kabf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/cec-videos/smiling_sad-nostalgia/kabf_smiling_sad-nostalgia.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sad-nostalgia/lekf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/cec-videos/smiling_sad-nostalgia/lekf_smiling_sad-nostalgia.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sad-nostalgia/milf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/cec-videos/smiling_sad-nostalgia/milf_smiling_sad-nostalgia.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sad-nostalgia/silf_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/cec-videos/smiling_sad-nostalgia/silf_smiling_sad-nostalgia.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sad-nostalgia/cawm_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/cec-videos/smiling_sad-nostalgia/cawm_smiling_sad-nostalgia.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sad-nostalgia/chsm_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/cec-videos/smiling_sad-nostalgia/chsm_smiling_sad-nostalgia.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sad-nostalgia/jakm_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/cec-videos/smiling_sad-nostalgia/jakm_smiling_sad-nostalgia.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sad-nostalgia/juhm_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/cec-videos/smiling_sad-nostalgia/juhm_smiling_sad-nostalgia.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sad-nostalgia/mamm_smiling_sad-nostalgia_%03d.png ~/.keras/datasets/cec-videos/smiling_sad-nostalgia/mamm_smiling_sad-nostalgia.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sardonic/islf_smiling_sardonic_%03d.png ~/.keras/datasets/cec-videos/smiling_sardonic/islf_smiling_sardonic.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sardonic/kabf_smiling_sardonic_%03d.png ~/.keras/datasets/cec-videos/smiling_sardonic/kabf_smiling_sardonic.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sardonic/lekf_smiling_sardonic_%03d.png ~/.keras/datasets/cec-videos/smiling_sardonic/lekf_smiling_sardonic.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sardonic/milf_smiling_sardonic_%03d.png ~/.keras/datasets/cec-videos/smiling_sardonic/milf_smiling_sardonic.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sardonic/silf_smiling_sardonic_%03d.png ~/.keras/datasets/cec-videos/smiling_sardonic/silf_smiling_sardonic.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sardonic/cawm_smiling_sardonic_%03d.png ~/.keras/datasets/cec-videos/smiling_sardonic/cawm_smiling_sardonic.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sardonic/chsm_smiling_sardonic_%03d.png ~/.keras/datasets/cec-videos/smiling_sardonic/chsm_smiling_sardonic.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sardonic/jakm_smiling_sardonic_%03d.png ~/.keras/datasets/cec-videos/smiling_sardonic/jakm_smiling_sardonic.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sardonic/juhm_smiling_sardonic_%03d.png ~/.keras/datasets/cec-videos/smiling_sardonic/juhm_smiling_sardonic.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_sardonic/mamm_smiling_sardonic_%03d.png ~/.keras/datasets/cec-videos/smiling_sardonic/mamm_smiling_sardonic.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_triumphant/islf_smiling_triumphant_%03d.png ~/.keras/datasets/cec-videos/smiling_triumphant/islf_smiling_triumphant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_triumphant/kabf_smiling_triumphant_%03d.png ~/.keras/datasets/cec-videos/smiling_triumphant/kabf_smiling_triumphant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_triumphant/lekf_smiling_triumphant_%03d.png ~/.keras/datasets/cec-videos/smiling_triumphant/lekf_smiling_triumphant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_triumphant/milf_smiling_triumphant_%03d.png ~/.keras/datasets/cec-videos/smiling_triumphant/milf_smiling_triumphant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_triumphant/silf_smiling_triumphant_%03d.png ~/.keras/datasets/cec-videos/smiling_triumphant/silf_smiling_triumphant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_triumphant/cawm_smiling_triumphant_%03d.png ~/.keras/datasets/cec-videos/smiling_triumphant/cawm_smiling_triumphant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_triumphant/chsm_smiling_triumphant_%03d.png ~/.keras/datasets/cec-videos/smiling_triumphant/chsm_smiling_triumphant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_triumphant/jakm_smiling_triumphant_%03d.png ~/.keras/datasets/cec-videos/smiling_triumphant/jakm_smiling_triumphant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_triumphant/juhm_smiling_triumphant_%03d.png ~/.keras/datasets/cec-videos/smiling_triumphant/juhm_smiling_triumphant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_triumphant/mamm_smiling_triumphant_%03d.png ~/.keras/datasets/cec-videos/smiling_triumphant/mamm_smiling_triumphant.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_uncertain/islf_smiling_uncertain_%03d.png ~/.keras/datasets/cec-videos/smiling_uncertain/islf_smiling_uncertain.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_uncertain/kabf_smiling_uncertain_%03d.png ~/.keras/datasets/cec-videos/smiling_uncertain/kabf_smiling_uncertain.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_uncertain/lekf_smiling_uncertain_%03d.png ~/.keras/datasets/cec-videos/smiling_uncertain/lekf_smiling_uncertain.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_uncertain/milf_smiling_uncertain_%03d.png ~/.keras/datasets/cec-videos/smiling_uncertain/milf_smiling_uncertain.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_uncertain/silf_smiling_uncertain_%03d.png ~/.keras/datasets/cec-videos/smiling_uncertain/silf_smiling_uncertain.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_uncertain/cawm_smiling_uncertain_%03d.png ~/.keras/datasets/cec-videos/smiling_uncertain/cawm_smiling_uncertain.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_uncertain/chsm_smiling_uncertain_%03d.png ~/.keras/datasets/cec-videos/smiling_uncertain/chsm_smiling_uncertain.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_uncertain/jakm_smiling_uncertain_%03d.png ~/.keras/datasets/cec-videos/smiling_uncertain/jakm_smiling_uncertain.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_uncertain/juhm_smiling_uncertain_%03d.png ~/.keras/datasets/cec-videos/smiling_uncertain/juhm_smiling_uncertain.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_uncertain/mamm_smiling_uncertain_%03d.png ~/.keras/datasets/cec-videos/smiling_uncertain/mamm_smiling_uncertain.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_winning/islf_smiling_winning_%03d.png ~/.keras/datasets/cec-videos/smiling_winning/islf_smiling_winning.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_winning/kabf_smiling_winning_%03d.png ~/.keras/datasets/cec-videos/smiling_winning/kabf_smiling_winning.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_winning/lekf_smiling_winning_%03d.png ~/.keras/datasets/cec-videos/smiling_winning/lekf_smiling_winning.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_winning/milf_smiling_winning_%03d.png ~/.keras/datasets/cec-videos/smiling_winning/milf_smiling_winning.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_winning/silf_smiling_winning_%03d.png ~/.keras/datasets/cec-videos/smiling_winning/silf_smiling_winning.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_winning/cawm_smiling_winning_%03d.png ~/.keras/datasets/cec-videos/smiling_winning/cawm_smiling_winning.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_winning/chsm_smiling_winning_%03d.png ~/.keras/datasets/cec-videos/smiling_winning/chsm_smiling_winning.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_winning/jakm_smiling_winning_%03d.png ~/.keras/datasets/cec-videos/smiling_winning/jakm_smiling_winning.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_winning/juhm_smiling_winning_%03d.png ~/.keras/datasets/cec-videos/smiling_winning/juhm_smiling_winning.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_winning/mamm_smiling_winning_%03d.png ~/.keras/datasets/cec-videos/smiling_winning/mamm_smiling_winning.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_yeah-right/islf_smiling_yeah-right_%03d.png ~/.keras/datasets/cec-videos/smiling_yeah-right/islf_smiling_yeah-right.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_yeah-right/kabf_smiling_yeah-right_%03d.png ~/.keras/datasets/cec-videos/smiling_yeah-right/kabf_smiling_yeah-right.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_yeah-right/lekf_smiling_yeah-right_%03d.png ~/.keras/datasets/cec-videos/smiling_yeah-right/lekf_smiling_yeah-right.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_yeah-right/milf_smiling_yeah-right_%03d.png ~/.keras/datasets/cec-videos/smiling_yeah-right/milf_smiling_yeah-right.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_yeah-right/silf_smiling_yeah-right_%03d.png ~/.keras/datasets/cec-videos/smiling_yeah-right/silf_smiling_yeah-right.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_yeah-right/cawm_smiling_yeah-right_%03d.png ~/.keras/datasets/cec-videos/smiling_yeah-right/cawm_smiling_yeah-right.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_yeah-right/chsm_smiling_yeah-right_%03d.png ~/.keras/datasets/cec-videos/smiling_yeah-right/chsm_smiling_yeah-right.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_yeah-right/jakm_smiling_yeah-right_%03d.png ~/.keras/datasets/cec-videos/smiling_yeah-right/jakm_smiling_yeah-right.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_yeah-right/juhm_smiling_yeah-right_%03d.png ~/.keras/datasets/cec-videos/smiling_yeah-right/juhm_smiling_yeah-right.avi
ffmpeg -y -i ~/.keras/large-mpi-db/smiling_yeah-right/mamm_smiling_yeah-right_%03d.png ~/.keras/datasets/cec-videos/smiling_yeah-right/mamm_smiling_yeah-right.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_considering/islf_considering_%03d.png ~/.keras/datasets/cec-videos/thinking_considering/islf_thinking_considering.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_considering/kabf_considering_%03d.png ~/.keras/datasets/cec-videos/thinking_considering/kabf_thinking_considering.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_considering/lekf_considering_%03d.png ~/.keras/datasets/cec-videos/thinking_considering/lekf_thinking_considering.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_considering/milf_considering_%03d.png ~/.keras/datasets/cec-videos/thinking_considering/milf_thinking_considering.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_considering/silf_considering_%03d.png ~/.keras/datasets/cec-videos/thinking_considering/silf_thinking_considering.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_considering/cawm_considering_%03d.png ~/.keras/datasets/cec-videos/thinking_considering/cawm_thinking_considering.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_considering/chsm_considering_%03d.png ~/.keras/datasets/cec-videos/thinking_considering/chsm_thinking_considering.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_considering/jakm_considering_%03d.png ~/.keras/datasets/cec-videos/thinking_considering/jakm_thinking_considering.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_considering/juhm_considering_%03d.png ~/.keras/datasets/cec-videos/thinking_considering/juhm_thinking_considering.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_considering/mamm_considering_%03d.png ~/.keras/datasets/cec-videos/thinking_considering/mamm_thinking_considering.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_problem-solving/islf_problem-solving_%03d.png ~/.keras/datasets/cec-videos/thinking_problem-solving/islf_thinking_problem-solving.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_problem-solving/kabf_problem-solving_%03d.png ~/.keras/datasets/cec-videos/thinking_problem-solving/kabf_thinking_problem-solving.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_problem-solving/lekf_problem-solving_%03d.png ~/.keras/datasets/cec-videos/thinking_problem-solving/lekf_thinking_problem-solving.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_problem-solving/milf_problem-solving_%03d.png ~/.keras/datasets/cec-videos/thinking_problem-solving/milf_thinking_problem-solving.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_problem-solving/silf_problem-solving_%03d.png ~/.keras/datasets/cec-videos/thinking_problem-solving/silf_thinking_problem-solving.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_problem-solving/cawm_problem-solving_%03d.png ~/.keras/datasets/cec-videos/thinking_problem-solving/cawm_thinking_problem-solving.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_problem-solving/chsm_problem-solving_%03d.png ~/.keras/datasets/cec-videos/thinking_problem-solving/chsm_thinking_problem-solving.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_problem-solving/jakm_problem-solving_%03d.png ~/.keras/datasets/cec-videos/thinking_problem-solving/jakm_thinking_problem-solving.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_problem-solving/juhm_problem-solving_%03d.png ~/.keras/datasets/cec-videos/thinking_problem-solving/juhm_thinking_problem-solving.avi
ffmpeg -y -i ~/.keras/large-mpi-db/thinking_problem-solving/mamm_problem-solving_%03d.png ~/.keras/datasets/cec-videos/thinking_problem-solving/mamm_thinking_problem-solving.avi
ffmpeg -y -i ~/.keras/large-mpi-db/tired/islf_tired_%03d.png ~/.keras/datasets/cec-videos/tired/islf_tired.avi
ffmpeg -y -i ~/.keras/large-mpi-db/tired/kabf_tired_%03d.png ~/.keras/datasets/cec-videos/tired/kabf_tired.avi
ffmpeg -y -i ~/.keras/large-mpi-db/tired/lekf_tired_%03d.png ~/.keras/datasets/cec-videos/tired/lekf_tired.avi
ffmpeg -y -i ~/.keras/large-mpi-db/tired/milf_tired_%03d.png ~/.keras/datasets/cec-videos/tired/milf_tired.avi
ffmpeg -y -i ~/.keras/large-mpi-db/tired/silf_tired_%03d.png ~/.keras/datasets/cec-videos/tired/silf_tired.avi
ffmpeg -y -i ~/.keras/large-mpi-db/tired/cawm_tired_%03d.png ~/.keras/datasets/cec-videos/tired/cawm_tired.avi
ffmpeg -y -i ~/.keras/large-mpi-db/tired/chsm_tired_%03d.png ~/.keras/datasets/cec-videos/tired/chsm_tired.avi
ffmpeg -y -i ~/.keras/large-mpi-db/tired/jakm_tired_%03d.png ~/.keras/datasets/cec-videos/tired/jakm_tired.avi
ffmpeg -y -i ~/.keras/large-mpi-db/tired/juhm_tired_%03d.png ~/.keras/datasets/cec-videos/tired/juhm_tired.avi
ffmpeg -y -i ~/.keras/large-mpi-db/tired/mamm_tired_%03d.png ~/.keras/datasets/cec-videos/tired/mamm_tired.avi
ffmpeg -y -i ~/.keras/large-mpi-db/treudoof_bambi-eyes/islf_treudoof_%03d.png ~/.keras/datasets/cec-videos/treudoof_bambi-eyes/islf_treudoof_bambi-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/treudoof_bambi-eyes/kabf_treudoof_%03d.png ~/.keras/datasets/cec-videos/treudoof_bambi-eyes/kabf_treudoof_bambi-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/treudoof_bambi-eyes/lekf_treudoof_%03d.png ~/.keras/datasets/cec-videos/treudoof_bambi-eyes/lekf_treudoof_bambi-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/treudoof_bambi-eyes/milf_treudoof_%03d.png ~/.keras/datasets/cec-videos/treudoof_bambi-eyes/milf_treudoof_bambi-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/treudoof_bambi-eyes/silf_treudoof_%03d.png ~/.keras/datasets/cec-videos/treudoof_bambi-eyes/silf_treudoof_bambi-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/treudoof_bambi-eyes/cawm_treudoof_%03d.png ~/.keras/datasets/cec-videos/treudoof_bambi-eyes/cawm_treudoof_bambi-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/treudoof_bambi-eyes/chsm_treudoof_%03d.png ~/.keras/datasets/cec-videos/treudoof_bambi-eyes/chsm_treudoof_bambi-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/treudoof_bambi-eyes/jakm_treudoof_%03d.png ~/.keras/datasets/cec-videos/treudoof_bambi-eyes/jakm_treudoof_bambi-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/treudoof_bambi-eyes/juhm_treudoof_%03d.png ~/.keras/datasets/cec-videos/treudoof_bambi-eyes/juhm_treudoof_bambi-eyes.avi
ffmpeg -y -i ~/.keras/large-mpi-db/treudoof_bambi-eyes/mamm_treudoof_%03d.png ~/.keras/datasets/cec-videos/treudoof_bambi-eyes/mamm_treudoof_bambi-eyes.avi